# Tests with:
#
# prefer_zero_one_indexing == "true"
# prefer_column_vectors    == "false"
# do_fortran_indexing      == "true"

# scalar tests

set test zero-one-tft-s-1
set prog_output "error:.*"
do_test s-1.m

set test zero-one-tft-s-2
set prog_output "ans = *1"
do_test s-2.m

set test zero-one-tft-s-3
set prog_output "ans = *1"
do_test s-3.m

set test zero-one-tft-s-4
set prog_output "ans = *1"
do_test s-4.m

# vector tests

set test zero-one-tft-v-1
set prog_output "ans = *1"
do_test v-1.m

set test zero-one-tft-v-2
set prog_output "ans = *1"
do_test v-2.m

set test zero-one-tft-v-3
set prog_output "ans = *1"
do_test v-3.m

set test zero-one-tft-v-4
set prog_output "ans = *1"
do_test v-4.m

# matrix tests

set test zero-one-tft-m-1
set prog_output "ans = *1"
do_test m-1.m

set test zero-one-tft-m-2
set prog_output "ans = *1"
do_test m-2.m

set test zero-one-tft-m-3
set prog_output "ans = *1"
do_test m-3.m

set test zero-one-tft-m-4
set prog_output "ans = *1"
do_test m-4.m

set test zero-one-tft-m-5
set prog_output "ans = *1"
do_test m-5.m

set test zero-one-tft-m-6
set prog_output "ans = *1"
do_test m-6.m

set test zero-one-tft-m-7
set prog_output "ans = *1"
do_test m-7.m

set test zero-one-tft-m-8
set prog_output "ans = *1"
do_test m-8.m

set test zero-one-tft-m-9
set prog_output "ans = *1"
do_test m-9.m

set test zero-one-tft-m-10
set prog_output "ans = *1"
do_test m-10.m

set test zero-one-tft-m-11
set prog_output "ans = *1"
do_test m-11.m

set test zero-one-tft-m-12
set prog_output "ans = *1"
do_test m-12.m

set test zero-one-tft-m-13
set prog_output "ans = *1"
do_test m-13.m

set test zero-one-tft-m-14
set prog_output "ans = *1"
do_test m-14.m

set test zero-one-tft-m-15
set prog_output "ans = *1"
do_test m-15.m

set test zero-one-tft-m-16
set prog_output "ans = *1"
do_test m-16.m

set test zero-one-tft-m-17
set prog_output "ans = *1"
do_test m-17.m

set test zero-one-tft-m-18
set prog_output "ans = *1"
do_test m-18.m

set test zero-one-tft-m-19
set prog_output "ans = *1"
do_test m-19.m

set test zero-one-tft-m-20
set prog_output "ans = *1"
do_test m-20.m

set test zero-one-tft-m-21
set prog_output "ans = *1"
do_test m-21.m

set test zero-one-tft-m-22
set prog_output "ans = *1"
do_test m-22.m

set test zero-one-tft-m-23
set prog_output "ans = *1"
do_test m-23.m

set test zero-one-tft-m-24
set prog_output "ans = *1"
do_test m-24.m

set test zero-one-tft-m-25
set prog_output "ans = *1"
do_test m-25.m

set test zero-one-tft-m-26
set prog_output "ans = *1"
do_test m-26.m

set test zero-one-tft-m-27
set prog_output "ans = *1"
do_test m-27.m

set test zero-one-tft-m-28
set prog_output "ans = *1"
do_test m-28.m

set test zero-one-tft-m-29
set prog_output "ans = *1"
do_test m-29.m

set test zero-one-tft-m-30
set prog_output "ans = *1"
do_test m-30.m

set test zero-one-tft-m-31
set prog_output "ans = *1"
do_test m-31.m

set test zero-one-tft-m-32
set prog_output "ans = *1"
do_test m-32.m

set test zero-one-tft-m-33
set prog_output "ans = *1"
do_test m-33.m

set test zero-one-tft-m-34
set prog_output "ans = *1"
do_test m-34.m

set test zero-one-tft-m-35
set prog_output "ans = *1"
do_test m-35.m

set test zero-one-tft-m-36
set prog_output "ans = *1"
do_test m-36.m
