set test fsolve-1
set prog_output "info good\nsolution good\nvalue good"
do_test fsolve-1.m

set test fsolve-2
set prog_output "info good\nsolution good\nvalue good"
do_test fsolve-2.m

set test fsolve_options-1
set prog_output "ans = 1"
do_test fsolve_options-1.m

set test fsolve_options-2
set prog_output "\n... quad_options:.*"
do_test fsolve_options-2.m

set test fsolve_options-3
set prog_output "\n... quad_options:.*"
do_test fsolve_options-3.m
