(isstr (strftime ("%%%n%t%H%I%k%l", localtime (time ())))
 && isstr (strftime ("%M%p%r%R%s%S%T", localtime (time ())))
 && isstr (strftime ("%X%Z%a%A%b%B%c", localtime (time ())))
 && isstr (strftime ("%C%d%e%D%h%j%m", localtime (time ())))
 && isstr (strftime ("%U%w%W%x%y%Y", localtime (time ()))))
