## The following functions need to have tests written for them:

# mkfifo
# system
# popen
# pclose
# fork
# exec
# pipe
# dup2
# waitpid
# fcntl

set test time-1
set prog_output "^ans = 1"
do_test time-1.m

set test ctime-1
set prog_output "^ans = 1"
do_test ctime-1.m

set test ctime-2
set prog_output "^usage:.*"
do_test ctime-2.m

set test ctime-3
set prog_output "^usage:.*"
do_test ctime-3.m

set test gmtime-1
set prog_output "^ans = 1"
do_test gmtime-1.m

set test gmtime-2
set prog_output "\n... gmtime:.*"
do_test gmtime-2.m

set test gmtime-3
set prog_output "\n... gmtime:.*"
do_test gmtime-3.m

set test localtime-1
set prog_output "^ans = 1"
do_test localtime-1.m

set test localtime-2
set prog_output "\n... localtime:.*"
do_test localtime-2.m

set test localtime-3
set prog_output "\n... localtime:.*"
do_test localtime-3.m

set test mktime-1
set prog_output "^ans = 1"
do_test mktime-1.m

set test mktime-2
set prog_output "\n... mktime:.*"
do_test mktime-2.m

set test mktime-3
set prog_output "\n... mktime:.*"
do_test mktime-3.m

set test asctime-1
set prog_output "^ans = 1"
do_test asctime-1.m

set test asctime-2
set prog_output "^usage:.*"
do_test asctime-2.m

set test asctime-3
set prog_output "^usage:.*"
do_test asctime-3.m

set test strftime-1
set prog_output "^ans = 1"
do_test strftime-1.m

set test strftime-2
set prog_output "\n... strftime:.*"
do_test strftime-2.m

set test strftime-3
set prog_output "\n... strftime:.*"
do_test strftime-3.m

set test clock-1
set prog_output "^ans = 1"
do_test clock-1.m

set test date-1
set prog_output "^ans = 1"
do_test date-1.m

set test etime-1
set prog_output "^ans = 1"
do_test etime-1.m

set test etime-2
set prog_output "^usage:.*"
do_test etime-2.m

set test etime-3
set prog_output "^usage:.*"
do_test etime-3.m

set test cputime-1
set prog_output "^ans = 1"
do_test cputime-1.m

set test is_leap_year-1
set prog_output "^ans = 1"
do_test is_leap_year-1.m

set test is_leap_year-2
set prog_output "^usage:.*"
do_test is_leap_year-2.m

set test tic-toc-1
set prog_output "^ans = 1"
do_test tic-toc-1.m

set test pause-1
set prog_output "ok"
do_test pause-1.m

set test pause-2
set prog_output "\n... pause:.*"
do_test pause-2.m

set test sleep-1
set prog_output "ok"
do_test sleep-1.m

set test sleep-2
set prog_output "\n... sleep:.*"
do_test sleep-2.m

set test sleep-3
set prog_output "\n... sleep:.*"
do_test sleep-3.m

set test usleep-1
set prog_output "ok"
do_test usleep-1.m

set test usleep-2
set prog_output "\n... usleep:.*"
do_test usleep-2.m

set test usleep-3
set prog_output "\n... usleep:.*"
do_test usleep-3.m

set test rename-1
set prog_output "ans = 1"
do_test rename-1.m

set test rename-2
set prog_output "\n... rename:.*"
do_test rename-2.m

set test rename-3
set prog_output "\n... rename:.*"
do_test rename-3.m

set test unlink-1
set prog_output "ans = 1"
do_test unlink-1.m

set test unlink-2
set prog_output "\n... unlink:.*"
do_test unlink-2.m

set test unlink-3
set prog_output "\n... unlink:.*"
do_test unlink-3.m

set test readdir-1
set prog_output "^ans = 1"
do_test readdir-1.m

set test readdir-2
set prog_output "\n... readdir:.*"
do_test readdir-2.m

set test readdir-3
set prog_output "\n... readdir:.*"
do_test readdir-3.m

set test mk-rm-dir-1
set prog_output "^ans = 1"
do_test mk-rm-dir-1.m

set test mkdir-1
set prog_output "\n... mkdir:.*"
do_test mkdir-1.m

set test mkdir-2
set prog_output "\n... mkdir:.*"
do_test mkdir-2.m

set test rmdir-1
set prog_output "\n... rmdir:.*"
do_test rmdir-1.m

set test rmdir-2
set prog_output "ans = 0"
do_test rmdir-2.m

set test umask-1
set prog_output "ans = 1"
do_test umask-1.m

set test umask-2
set prog_output "\n... umask:.*"
do_test umask-2.m

set test umask-3
set prog_output "\n... umask:.*"
do_test umask-3.m

set test stat-1
set prog_output "^ans = 1"
do_test stat-1.m

set test stat-2
set prog_output "\n... stat:.*"
do_test stat-2.m

set test stat-3
set prog_output "\n... stat:.*"
do_test stat-3.m

set test lstat-1
set prog_output "^ans = 1"
do_test lstat-1.m

set test lstat-2
set prog_output "\n... lstat:.*"
do_test lstat-2.m

set test lstat-3
set prog_output "\n... lstat:.*"
do_test lstat-3.m

set test glob-1
set prog_output "^ans = 1"
do_test glob-1.m

set test glob-2
set prog_output "\n... glob:*"
do_test glob-2.m

set test glob-3
set prog_output "\n... glob:.*"
do_test glob-3.m

set test fnmatch-1
set prog_output "^ans = 1"
do_test fnmatch-1.m

set test fnmatch-2
set prog_output "\n... fnmatch:.*"
do_test fnmatch-2.m

set test fnmatch-3
set prog_output "\n... fnmatch:.*"
do_test fnmatch-3.m

set test file_in_path-1
set prog_output "^ans = 1"
do_test file_in_path-1.m

set test file_in_path-2
set prog_output "^warning:.*\nerror:.*"
do_test file_in_path-2.m

set test file_in_path-3
set prog_output "\n... file_in_path:.*"
do_test file_in_path-3.m

set test file_in_path-4
set prog_output "\n... file_in_path:.*"
do_test file_in_path-4.m

set test tilde_expand-1
set prog_output "^ans = 1"
do_test tilde_expand-1.m

set test tilde_expand-2
set prog_output "\n... tilde_expand:.*"
do_test tilde_expand-2.m

set test tilde_expand-3
set prog_output "\n... tilde_expand:.*"
do_test tilde_expand-3.m

set test getpgrp-1
set prog_output "^ans = 1"
do_test getpgrp-1.m

set test getpgrp-2
set prog_output "\n... getpgrp"
do_test getpgrp-2.m

set test getpid-1
set prog_output "^ans = 1"
do_test getpid-1.m

set test getpid-2
set prog_output "\n... getpid"
do_test getpid-2.m

set test getppid-1
set prog_output "^ans = 1"
do_test getppid-1.m

set test getppid-2
set prog_output "\n... getppid"
do_test getppid-2.m

set test geteuid-1
set prog_output "^ans = 1"
do_test geteuid-1.m

set test geteuid-2
set prog_output "\n... geteuid"
do_test geteuid-2.m

set test getuid-1
set prog_output "^ans = 1"
do_test getuid-1.m

set test getuid-2
set prog_output "\n... getuid"
do_test getuid-2.m

set test getegid-1
set prog_output "^ans = 1"
do_test getegid-1.m

set test getegid-2
set prog_output "\n... getegid"
do_test getegid-2.m

set test getgid-1
set prog_output "^ans = 1"
do_test getgid-1.m

set test getgid-2
set prog_output "\n... getgid"
do_test getgid-2.m

set test getenv-1
set prog_output "^ans = 1"
do_test getenv-1.m

set test getenv-2
set prog_output "\n... getenv:.*"
do_test getenv-2.m

set test getenv-3
set prog_output "\n... getenv:.*"
do_test getenv-3.m

set test getenv-4
set prog_output "^warning:.*"
do_test getenv-4.m

set test putenv-1
set prog_output "^ans = 1"
do_test putenv-1.m

set test putenv-2
set prog_output "\n... putenv:.*"
do_test putenv-2.m

set test putenv-3
set prog_output "\n... putenv:.*"
do_test putenv-3.m

set test putenv-4
set prog_output "^warning:.*"
do_test putenv-4.m

set test cd-1
set prog_output "^ans = 1"
do_test cd-1.m

set test cd-2
set prog_output "^error:.*"
do_test cd-2.m

set test pwd-1
set prog_output "^ans = 1"
do_test pwd-1.m

set test ls-1
set prog_output "^error:.*"
do_test ls-1.m

set test getpwent-1
set prog_output "^ans = 1"
do_test getpwent-1.m

set test getpwent-2
set prog_output "\n... getpwent:.*"
do_test getpwent-2.m

set test getpwuid-1
set prog_output "^ans = 1"
do_test getpwuid-1.m

set test getpwuid-2
set prog_output "\n... getpwuid:.*"
do_test getpwuid-2.m

set test getpwuid-3
set prog_output "\n... getpwuid:.*"
do_test getpwuid-3.m

set test getpwnam-1
set prog_output "^ans = 1"
do_test getpwnam-1.m

set test getpwnam-2
set prog_output "\n... getpwnam:.*"
do_test getpwnam-2.m

set test getpwnam-3
set prog_output "\n... getpwnam:.*"
do_test getpwnam-3.m

set test setpwent-1
set prog_output "^ans = 1"
do_test setpwent-1.m

set test setpwent-2
set prog_output "\n... setpwent:.*"
do_test setpwent-2.m

set test endpwent-1
set prog_output "\n... endpwent:.*"
do_test endpwent-1.m

set test getgrent-1
set prog_output "^ans = 1"
do_test getgrent-1.m

set test getgrent-2
set prog_output "\n... getgrent:.*"
do_test getgrent-2.m

set test getgrgid-1
set prog_output "^ans = 1"
do_test getgrgid-1.m

set test getgrgid-2
set prog_output "\n... getgrgid:.*"
do_test getgrgid-2.m

set test getgrgid-3
set prog_output "\n... getgrgid:.*"
do_test getgrgid-3.m

set test getgrnam-1
set prog_output "^ans = 1"
do_test getgrnam-1.m

set test getgrnam-2
set prog_output "\n... getgrnam:.*"
do_test getgrnam-2.m

set test getgrnam-3
set prog_output "\n... getgrnam:.*"
do_test getgrnam-3.m

set test setgrent-1
set prog_output "^ans = 1"
do_test setgrent-1.m

set test setgrent-2
set prog_output "\n... setgrent:.*"
do_test setgrent-2.m

set test endgrent-1
set prog_output "\n... endgrent:.*"
do_test endgrent-1.m

set test computer-1
set prog_output "^ans = 1"
do_test computer-1.m

set test computer-2
set prog_output "^warning:.*"
do_test computer-2.m

set test isieee-1
set prog_output "^ans = 1"
do_test isieee-1.m

set test version-1
set prog_output "^ans = 1"
do_test version-1.m

set test version-2
set prog_output "^warning:.*"
do_test version-2.m

set test octave_config_info-1
set prog_output "^ans = 1"
do_test octave_config_info-1.m

set test getrusage-1
set prog_output "^ans = 1"
do_test getrusage-1.m
