set test time-1
set prog_output "ans = 1"
do_test time-1.m

# ctime
# gmtime
# localtime
# mktime
# asctime
# strftime
# clock
# date
# etime
# cputime
# is_leap_year
# tic-toc
# pause
# sleep
# usleep
# rename
# unlink
# readdir
# mkdir
# mkfifo
# umask
# stat
# lstat
# glob
# fnmatch
# file_in_path
# tilde_expand
# system
# popen
# pclose
# fork
# exec
# pipe
# dup2
# waitpid
# fcntl

set test getpgrp-1
set prog_output "ans = 1"
do_test getpgrp-1.m

set test getpgrp-2
set prog_output "\n... getpgrp"
do_test getpgrp-2.m

set test getpid-1
set prog_output "ans = 1"
do_test getpid-1.m

set test getpid-2
set prog_output "\n... getpid"
do_test getpid-2.m

set test getppid-1
set prog_output "ans = 1"
do_test getppid-1.m

set test getppid-2
set prog_output "\n... getppid"
do_test getppid-2.m

set test geteuid-1
set prog_output "ans = 1"
do_test geteuid-1.m

set test geteuid-2
set prog_output "\n... geteuid"
do_test geteuid-2.m

set test getuid-1
set prog_output "ans = 1"
do_test getuid-1.m

set test getuid-2
set prog_output "\n... getuid"
do_test getuid-2.m

set test getegid-1
set prog_output "ans = 1"
do_test getegid-1.m

set test getegid-2
set prog_output "\n... getegid"
do_test getegid-2.m

set test getgid-1
set prog_output "ans = 1"
do_test getgid-1.m

set test getgid-2
set prog_output "\n... getgid"
do_test getgid-2.m

set test getenv-1
set prog_output "ans = 1"
do_test getenv-1.m

set test getenv-2
set prog_output "\n... getenv:.*"
do_test getenv-2.m

set test getenv-3
set prog_output "\n... getenv:.*"
do_test getenv-3.m

set test getenv-4
set prog_output "error:.*"
do_test getenv-4.m

set test putenv-1
set prog_output "ans = 1"
do_test putenv-1.m

set test putenv-2
set prog_output "\n... putenv:.*"
do_test putenv-2.m

set test putenv-3
set prog_output "\n... putenv:.*"
do_test putenv-3.m

set test putenv-4
set prog_output "error:.*"
do_test putenv-4.m

set test cd-1
set prog_output "ans = 1"
do_test cd-1.m

set test cd-2
set prog_output "error:.*"
do_test cd-2.m

set test pwd-1
set prog_output "ans = 1"
do_test pwd-1.m

set test ls-1
set prog_output "error:.*"
do_test ls-1.m

set test getpwent-1
set prog_output "ans = 1"
do_test getpwent-1.m

set test getpwent-2
set prog_output "\n... getpwent:.*"
do_test getpwent-2.m

set test getpwuid-1
set prog_output "ans = 1"
do_test getpwuid-1.m

set test getpwuid-2
set prog_output "\n... getpwuid:.*"
do_test getpwuid-2.m

set test getpwuid-3
set prog_output "\n... getpwuid:.*"
do_test getpwuid-3.m

set test getpwnam-1
set prog_output "ans = 1"
do_test getpwnam-1.m

set test getpwnam-2
set prog_output "\n... getpwnam:.*"
do_test getpwnam-2.m

set test getpwnam-3
set prog_output "\n... getpwnam:.*"
do_test getpwnam-3.m

set test setpwent-1
set prog_output "ans = 1"
do_test setpwent-1.m

set test setpwent-2
set prog_output "\n... setpwent:.*"
do_test setpwent-2.m

set test endpwent-1
set prog_output "\n... endpwent:.*"
do_test endpwent-1.m

set test getgrent-1
set prog_output "ans = 1"
do_test getgrent-1.m

set test getgrent-2
set prog_output "\n... getgrent:.*"
do_test getgrent-2.m

set test getgrgid-1
set prog_output "ans = 1"
do_test getgrgid-1.m

set test getgrgid-2
set prog_output "\n... getgrgid:.*"
do_test getgrgid-2.m

set test getgrgid-3
set prog_output "\n... getgrgid:.*"
do_test getgrgid-3.m

set test getgrnam-1
set prog_output "ans = 1"
do_test getgrnam-1.m

set test getgrnam-2
set prog_output "\n... getgrnam:.*"
do_test getgrnam-2.m

set test getgrnam-3
set prog_output "\n... getgrnam:.*"
do_test getgrnam-3.m

set test setgrent-1
set prog_output "ans = 1"
do_test setgrent-1.m

set test setgrent-2
set prog_output "\n... setgrent:.*"
do_test setgrent-2.m

set test endgrent-1
set prog_output "\n... endgrent:.*"
do_test endgrent-1.m

set test computer-1
set prog_output "ans = 1"
do_test computer-1.m

set test computer-2
set prog_output "warning:.*"
do_test computer-2.m

set test isieee-1
set prog_output "ans = 1"
do_test isieee-1.m

set test version-1
set prog_output "ans = 1"
do_test version-1.m

set test version-2
set prog_output "warning:.*"
do_test version-2.m

set test octave_config_info-1
set prog_output "ans = 1"
do_test octave_config_info-1.m

set test getrusage-1
set prog_output "ans = 1"
do_test getrusage-1.m
