EXTRA_DIST += amos/module.mk

libcruft_la_SOURCES += \
  amos/cacai.f \
  amos/cacon.f \
  amos/cbesh.f \
  amos/cbesi.f \
  amos/cbesj.f \
  amos/cbesk.f \
  amos/cbesy.f \
  amos/cbinu.f \
  amos/cbuni.f \
  amos/cbunk.f \
  amos/cunk1.f \
  amos/cunk2.f \
  amos/crati.f \
  amos/cshch.f \
  amos/cuni1.f \
  amos/cuoik.f \
  amos/cairy.f \
  amos/cbiry.f \
  amos/ckscl.f \
  amos/cs1s2.f \
  amos/cuchk.f \
  amos/cuni2.f \
  amos/cwrsk.f \
  amos/casyi.f \
  amos/cbknu.f \
  amos/cmlri.f \
  amos/cseri.f \
  amos/cunhj.f \
  amos/cunik.f \
  amos/dgamln.f \
  amos/gamln.f \
  amos/xzabs.f \
  amos/xzexp.f \
  amos/xzlog.f \
  amos/xzsqrt.f \
  amos/zacai.f \
  amos/zacon.f \
  amos/zairy.f \
  amos/zasyi.f \
  amos/zbesh.f \
  amos/zbesi.f \
  amos/zbesj.f \
  amos/zbesk.f \
  amos/zbesy.f \
  amos/zbinu.f \
  amos/zbiry.f \
  amos/zbknu.f \
  amos/zbuni.f \
  amos/zbunk.f \
  amos/zdiv.f \
  amos/zkscl.f \
  amos/zmlri.f \
  amos/zmlt.f \
  amos/zrati.f \
  amos/zs1s2.f \
  amos/zseri.f \
  amos/zshch.f \
  amos/zuchk.f \
  amos/zunhj.f \
  amos/zuni1.f \
  amos/zuni2.f \
  amos/zunik.f \
  amos/zunk1.f \
  amos/zunk2.f \
  amos/zuoik.f \
  amos/zwrsk.f
