compile_TEST_FILES = \
  %reldir%/bytecode.tst \
  %reldir%/bytecode_ans.m \
  %reldir%/bytecode_assign.m \
  %reldir%/bytecode_binops.m \
  %reldir%/bytecode_anon_handles.m \
  %reldir%/bytecode_cdef_use.m \
  %reldir%/bytecode_cell.m \
  %reldir%/bytecode_dountil.m \
  %reldir%/bytecode_end.m \
  %reldir%/bytecode_errors.m \
  %reldir%/bytecode_eval_1.m \
  %reldir%/bytecode_evalin_1.m \
  %reldir%/bytecode_evalin_2.m \
  %reldir%/bytecode_for.m \
  %reldir%/bytecode_global_1.m \
  %reldir%/bytecode_if.m \
  %reldir%/bytecode_index_obj.m \
  %reldir%/bytecode_inputname.m \
  %reldir%/bytecode_leaks.m \
  %reldir%/bytecode_matrix.m \
  %reldir%/bytecode_misc.m \
  %reldir%/bytecode_multi_assign.m \
  %reldir%/bytecode_nested.m \
  %reldir%/bytecode_persistant.m \
  %reldir%/bytecode_range.m \
  %reldir%/bytecode_return.m \
  %reldir%/bytecode_scripts.m \
  %reldir%/bytecode_script_topscope.m \
  %reldir%/bytecode_script_topscope_assert.m \
  %reldir%/bytecode_script_topscope_setup.m \
  %reldir%/bytecode_script_topscope_setup_script.m \
  %reldir%/bytecode_struct.m \
  %reldir%/bytecode_subfuncs.m \
  %reldir%/bytecode_subsasgn.m \
  %reldir%/bytecode_switch.m \
  %reldir%/bytecode_trycatch.m \
  %reldir%/bytecode_unary.m \
  %reldir%/bytecode_unwind.m \
  %reldir%/bytecode_varargin.m \
  %reldir%/bytecode_varargout.m \
  %reldir%/bytecode_while.m \
  %reldir%/bytecode_wordlistcmd.m \
  %reldir%/cdef_bar.m \
  %reldir%/cdef_foo.m \
  %reldir%/inputname_args.m \
  %reldir%/just_call_handle_with_arg.m \
  %reldir%/return_isargout.m \
  %reldir%/script1.m \
  %reldir%/script11.m \
  %reldir%/script2.m \
  %reldir%/script3.m \
  %reldir%/shutup_operator_test/@double/display.m \
  %reldir%/shutup_operator_test/@logical/display.m \
  %reldir%/shutup_operator_test/bytecode_disp.m \
  %reldir%/shutup_operator_test/bytecode_disp.tst \
  %reldir%/wrongname_fn.m

TEST_FILES += $(compile_TEST_FILES)
