## The following functions need to have tests written for them:

# disp
# fputs
# fgetl
# fgets
# fprintf
# fscanf
# ferror

set test load-save-1
set prog_output "^ans = 1"
do_test load-save.m

set test puts-1
set prog_output "foo\nans = 0"
do_test puts-1.m

set test puts-2
set prog_output "^ans = -1"
do_test puts-2.m

set test puts-3
set prog_output "\n... puts:.*"
do_test puts-3.m

set test puts-4
set prog_output "\n... puts:.*"
do_test puts-4.m

set test sscanf-1
set prog_output "^ans = 1"
do_test sscanf-1.m

set test sscanf-2
set prog_output "\n... sscanf:.*"
do_test sscanf-2.m

set test sscanf-3
set prog_output "^error:.*"
do_test sscanf-3.m

set test sscanf-4
set prog_output "\n... sscanf:.*"
do_test sscanf-4.m

set test sscanf-5
set prog_output "^ans = 1"
do_test sscanf-5.m

set test printf-1
set prog_output "test: 1\nx = 8"
do_test printf-1.m

set test printf-2
set prog_output "^error:.*"
do_test printf-2.m

set test printf-3
set prog_output "\n... printf:.*"
do_test printf-3.m

set test sprintf-1
set prog_output "^ans = 1"
do_test sprintf-1.m

set test sprintf-2
set prog_output "^error:.*"
do_test sprintf-2.m

set test sprintf-3
set prog_output "\n... sprintf:."
do_test sprintf-3.m

set test fopen-1
set prog_output "ans = 1"
do_test fopen-1.m

set test fopen-2
set prog_output "^error:.*"
do_test fopen-2.m

set test fopen-3
set prog_output "^error:.*"
do_test fopen-3.m

set test fopen-4
set prog_output "error:.*"
do_test fopen-4.m

set test fopen-5
set prog_output "\n... fopen:.*"
do_test fopen-5.m

set test fopen-6
set prog_output "\n... fopen:.*"
do_test fopen-6.m

set test fclose-1
set prog_output "^error:.*"
do_test fclose-1.m

set test fclose-2
set prog_output "\n... fclose:.*"
do_test fclose-2.m

set test tmpnam-1
set prog_output "^ans = 1"
do_test tmpnam-1.m

set test tmpnam-2
set prog_output "^warning:.*"
do_test tmpnam-2.m

set test tmpnam-3
set prog_output "^warning:.*"
do_test tmpnam-3.m

set test tmpnam-4
set prog_output "\n... tmpnam:.*"
do_test tmpnam-4.m

## set test file-io-1
## set prog_output "ok"
## do_test file-io-1.m

set test binary-io-1
set prog_output "ok"
do_test binary-io-1.m

set test file-pos-1
set prog_output "ok"
do_test file-pos-1.m

set test fputs-1
set prog_output "\n... fputs:.*"
do_test fputs-1.m

set test fputs-2
set prog_output "\n... fputs:.*"
do_test fputs-2.m

set test fputs-3
set prog_output "^ans = -1"
do_test fputs-3.m

set test fgetl-1
set prog_output "\n... fgetl:.*"
do_test fgetl-1.m

set test fgetl-2
set prog_output "\n... fgetl:.*"
do_test fgetl-2.m

set test fgetl-3
set prog_output "^error:.*"
do_test fgetl-3.m

set test fgets-1
set prog_output "\n... fgets:.*"
do_test fgets-1.m

set test fgets-2
set prog_output "\n... fgets:.*"
do_test fgets-2.m

set test fgets-3
set prog_output "^error:.*"
do_test fgets-3.m

set test fprintf-1
set prog_output "\n... fprintf:.*"
do_test fprintf-1.m

set test fprintf-2
set prog_output "\n... fprintf:.*"
do_test fprintf-2.m

set test fprintf-3
set prog_output "\n... fprintf:.*"
do_test fprintf-3.m

set test fprintf-4
set prog_output "^error:.*"
do_test fprintf-4.m

set test fprintf-5
set prog_output "^error:.*"
do_test fprintf-5.m

set test fscanf-1
set prog_output "\n... fscanf:.*"
do_test fscanf-1.m

set test fscanf-2
set prog_output "\n... fscanf:.*"
do_test fscanf-2.m

set test fscanf-3
set prog_output "^error:.*"
do_test fscanf-3.m

set test fread-1
set prog_output "\n... fread:.*"
do_test fread-1.m

set test fread-2
set prog_output "\n... fread:.*"
do_test fread-2.m

set test fread-3
set prog_output "^error:.*"
do_test fread-3.m

set test fwrite-1
set prog_output "\n... fwrite:.*"
do_test fwrite-1.m

set test fwrite-2
set prog_output "\n... fwrite:.*"
do_test fwrite-2.m

set test fwrite-3
set prog_output "^error:.*"
do_test fwrite-3.m

set test feof-1
set prog_output "\n... feof:.*"
do_test feof-1.m

set test feof-2
set prog_output "\n... feof:.*"
do_test feof-2.m

set test feof-3
set prog_output "^error:.*"
do_test feof-3.m

set test ferror-1
set prog_output "\n... ferror:.*"
do_test ferror-1.m

set test ferror-2
set prog_output "\n... ferror:.*"
do_test ferror-2.m

set test ferror-3
set prog_output "^error:.*"
do_test ferror-3.m

set test ftell-1
set prog_output "\n... ftell:.*"
do_test ftell-1.m

set test ftell-2
set prog_output "\n... ftell:.*"
do_test ftell-2.m

set test ftell-3
set prog_output "^error:.*"
do_test ftell-3.m

set test fseek-1
set prog_output "\n... fseek:.*"
do_test fseek-1.m

set test fseek-2
set prog_output "\n... fseek:.*"
do_test fseek-2.m

set test fseek-3
set prog_output "^error:.*"
do_test fseek-3.m

set test frewind-1
set prog_output "\n... frewind:.*"
do_test frewind-1.m

set test frewind-2
set prog_output "\n... frewind:.*"
do_test frewind-2.m

set test frewind-3
set prog_output "^error:.*"
do_test frewind-3.m
