FCN_FILE_DIRS += plot

plot_GEN_FCN_FILES = \
  plot/gnuplot_binary.m

GEN_FCN_FILES += $(plot_GEN_FCN_FILES)

plot_PRIVATE_FCN_FILES = \
  plot/private/__actual_axis_position__.m \
  plot/private/__add_datasource__.m \
  plot/private/__add_default_menu__.m \
  plot/private/__axes_limits__.m \
  plot/private/__axis_label__.m \
  plot/private/__bar__.m \
  plot/private/__clabel__.m \
  plot/private/__color_str_rgb__.m \
  plot/private/__contour__.m \
  plot/private/__default_plot_options__.m \
  plot/private/__errcomm__.m \
  plot/private/__errplot__.m \
  plot/private/__ezplot__.m \
  plot/private/__file_filter__.m \
  plot/private/__fltk_file_filter__.m \
  plot/private/__fltk_ginput__.m \
  plot/private/__fltk_print__.m \
  plot/private/__getlegenddata__.m \
  plot/private/__ghostscript__.m \
  plot/private/__gnuplot_get_var__.m \
  plot/private/__gnuplot_ginput__.m \
  plot/private/__gnuplot_has_feature__.m \
  plot/private/__gnuplot_has_terminal__.m\
  plot/private/__gnuplot_open_stream__.m \
  plot/private/__gnuplot_print__.m \
  plot/private/__gnuplot_version__.m \
  plot/private/__go_draw_axes__.m \
  plot/private/__go_draw_figure__.m \
  plot/private/__interp_cube__.m \
  plot/private/__is_function__.m \
  plot/private/__line__.m \
  plot/private/__marching_cube__.m \
  plot/private/__next_line_color__.m \
  plot/private/__next_line_style__.m \
  plot/private/__patch__.m \
  plot/private/__pie__.m \
  plot/private/__plt__.m \
  plot/private/__pltopt__.m \
  plot/private/__print_parse_opts__.m \
  plot/private/__quiver__.m \
  plot/private/__scatter__.m \
  plot/private/__stem__.m \
  plot/private/__tight_eps_bbox__.m \
  plot/private/__uigetdir_fltk__.m \
  plot/private/__uigetfile_fltk__.m \
  plot/private/__uiputfile_fltk__.m \
  plot/private/__uiobject_split_args__.m

plot_FCN_FILES = \
  plot/__gnuplot_drawnow__.m \
  plot/__plt_get_axis_arg__.m \
  plot/allchild.m \
  plot/ancestor.m \
  plot/area.m \
  plot/axes.m \
  plot/axis.m \
  plot/bar.m \
  plot/barh.m \
  plot/box.m \
  plot/caxis.m \
  plot/cla.m \
  plot/clabel.m \
  plot/clf.m \
  plot/close.m \
  plot/closereq.m \
  plot/colorbar.m \
  plot/colstyle.m \
  plot/comet.m \
  plot/comet3.m \
  plot/compass.m \
  plot/contour.m \
  plot/contour3.m \
  plot/contourc.m \
  plot/contourf.m \
  plot/cylinder.m \
  plot/daspect.m \
  plot/diffuse.m \
  plot/ellipsoid.m \
  plot/errorbar.m \
  plot/ezcontour.m \
  plot/ezcontourf.m \
  plot/ezmesh.m \
  plot/ezmeshc.m \
  plot/ezplot.m \
  plot/ezplot3.m \
  plot/ezpolar.m \
  plot/ezsurf.m \
  plot/ezsurfc.m \
  plot/feather.m \
  plot/figure.m \
  plot/fill.m \
  plot/findall.m \
  plot/findobj.m \
  plot/fplot.m \
  plot/gca.m \
  plot/gcbf.m \
  plot/gcbo.m \
  plot/gcf.m \
  plot/ginput.m \
  plot/graphics_toolkit.m \
  plot/grid.m \
  plot/gtext.m \
  plot/guidata.m \
  plot/guihandles.m \
  plot/hggroup.m \
  plot/hidden.m \
  plot/hist.m \
  plot/hold.m \
  plot/isfigure.m \
  plot/ishghandle.m \
  plot/ishold.m \
  plot/isocolors.m \
  plot/isonormals.m \
  plot/isosurface.m \
  plot/isprop.m \
  plot/legend.m \
  plot/line.m \
  plot/linkprop.m \
  plot/loglog.m \
  plot/loglogerr.m \
  plot/mesh.m \
  plot/meshc.m \
  plot/meshgrid.m \
  plot/meshz.m \
  plot/ndgrid.m \
  plot/newplot.m \
  plot/orient.m \
  plot/pareto.m \
  plot/patch.m \
  plot/pbaspect.m \
  plot/pcolor.m \
  plot/peaks.m \
  plot/pie.m \
  plot/pie3.m \
  plot/plot.m \
  plot/plot3.m \
  plot/plotmatrix.m \
  plot/plotyy.m \
  plot/polar.m \
  plot/print.m \
  plot/quiver.m \
  plot/quiver3.m \
  plot/rectangle.m \
  plot/refresh.m \
  plot/refreshdata.m \
  plot/ribbon.m \
  plot/rose.m \
  plot/saveas.m \
  plot/scatter.m \
  plot/scatter3.m \
  plot/semilogx.m \
  plot/semilogxerr.m \
  plot/semilogy.m \
  plot/semilogyerr.m \
  plot/shading.m \
  plot/shg.m \
  plot/slice.m \
  plot/sombrero.m \
  plot/specular.m \
  plot/sphere.m \
  plot/stairs.m \
  plot/stem.m \
  plot/stem3.m \
  plot/subplot.m \
  plot/surf.m \
  plot/surface.m \
  plot/surfc.m \
  plot/surfl.m \
  plot/surfnorm.m \
  plot/text.m \
  plot/title.m \
  plot/trimesh.m \
  plot/triplot.m \
  plot/trisurf.m \
  plot/uicontextmenu.m \
  plot/uicontrol.m \
  plot/uigetdir.m \
  plot/uigetfile.m \
  plot/uimenu.m \
  plot/uipanel.m \
  plot/uipushtool.m \
  plot/uiputfile.m \
  plot/uiresume.m \
  plot/uitoggletool.m \
  plot/uitoolbar.m \
  plot/uiwait.m \
  plot/view.m \
  plot/waitbar.m \
  plot/waitforbuttonpress.m \
  plot/whitebg.m \
  plot/xlabel.m \
  plot/xlim.m \
  plot/ylabel.m \
  plot/ylim.m \
  plot/zlabel.m \
  plot/zlim.m \
  $(plot_PRIVATE_FCN_FILES)

FCN_FILES += $(plot_FCN_FILES)

PKG_ADD_FILES += plot/PKG_ADD

DIRSTAMP_FILES += plot/$(octave_dirstamp)
