set test ismatrix-1
set prog_output "ans = 1"
do_test ismatrix-1.m

set test ismatrix-2
set prog_output "ans = 1"
do_test ismatrix-2.m

set test ismatrix-3
set prog_output "ans = 1"
do_test ismatrix-3.m

set test ismatrix-4
set prog_output "ans = 1"
do_test ismatrix-4.m

set test ismatrix-5
set prog_output "ans = 0"
do_test ismatrix-5.m

set test ismatrix-6
set prog_output "ans = 0"
do_test ismatrix-6.m

set test ismatrix-7
set prog_output "ans = 0"
do_test ismatrix-7.m

set test ismatrix-8
set prog_output "ans = 0"
do_test ismatrix-8.m

set test ismatrix-9
set prog_output "\n... ismatrix:.*"
do_test ismatrix-9.m

set test ismatrix-10
set prog_output "\n... ismatrix:.*"
do_test ismatrix-10.m

set test isvector-1
set prog_output "ans = 1"
do_test isvector-1.m

set test isvector-2
set prog_output "ans = 1"
do_test isvector-2.m

set test isvector-3
set prog_output "ans = 0"
do_test isvector-3.m

set test isvector-4
set prog_output "ans = 0"
do_test isvector-4.m

set test isvector-5
set prog_output "ans = 0"
do_test isvector-5.m

set test isvector-6
set prog_output "ans = 0"
do_test isvector-6.m

set test isvector-7
set prog_output "ans = 0"
do_test isvector-7.m

set test isvector-8
set prog_output "ans = 0"
do_test isvector-8.m

set test isvector-9
set prog_output "error:.*"
do_test isvector-9.m

set test isvector-10
set prog_output "error:.*"
do_test isvector-10.m

set test isscalar-1
set prog_output "ans = 1"
do_test isscalar-1.m

set test isscalar-2
set prog_output "ans = 0"
do_test isscalar-2.m

set test isscalar-3
set prog_output "ans = 0"
do_test isscalar-3.m

set test isscalar-4
set prog_output "ans = 0"
do_test isscalar-4.m

set test isscalar-5
set prog_output "ans = 0"
do_test isscalar-5.m

set test isscalar-6
set prog_output "ans = 0"
do_test isscalar-6.m

set test isscalar-7
set prog_output "ans = 0"
do_test isscalar-7.m

set test isscalar-8
set prog_output "ans = 0"
do_test isscalar-8.m

set test isscalar-9
set prog_output "error:.*"
do_test isscalar-9.m

set test isscalar-10
set prog_output "error:.*"
do_test isscalar-10.m

set test issquare-1
set prog_output "ans = 1"
do_test issquare-1.m

set test issquare-2
set prog_output "ans = 0"
do_test issquare-2.m

set test issquare-3
set prog_output "ans = 0"
do_test issquare-3.m

set test issquare-4
set prog_output "ans = 1"
do_test issquare-4.m

set test issquare-5
set prog_output "ans = 0"
do_test issquare-5.m

set test issquare-6
set prog_output "ans = 0"
do_test issquare-6.m

set test issquare-7
set prog_output "ans = 0"
do_test issquare-7.m

set test issquare-8
set prog_output "ans = 0"
do_test issquare-8.m

set test issquare-9
set prog_output "ans = 0"
do_test issquare-9.m

set test issquare-10
set prog_output "error:.*"
do_test issquare-10.m

set test issquare-11
set prog_output "error:.*"
do_test issquare-11.m

set test issymmetric-1
set prog_output "ans = 1"
do_test issymmetric-1.m

set test issymmetric-2
set prog_output "ans = 0"
do_test issymmetric-2.m

set test issymmetric-3
set prog_output "ans = 0"
do_test issymmetric-3.m

set test issymmetric-4
set prog_output "ans = 1"
do_test issymmetric-4.m

set test issymmetric-5
set prog_output "ans = 0"
do_test issymmetric-5.m

set test issymmetric-6
set prog_output "ans = 0"
do_test issymmetric-6.m

set test issymmetric-7
set prog_output "ans = 0"
do_test issymmetric-7.m

set test issymmetric-8
set prog_output "ans = 0"
do_test issymmetric-8.m

set test issymmetric-9
set prog_output "ans = 1"
do_test issymmetric-9.m

set test issymmetric-10
set prog_output "error:.*"
do_test issymmetric-10.m

set test issymmetric-11
set prog_output "error:.*"
do_test issymmetric-11.m
