EXTRA_DIST += OPERATORS/module.mk

OPERATORS_SRC = \
  OPERATORS/op-b-b.cc \
  OPERATORS/op-b-bm.cc \
  OPERATORS/op-b-sbm.cc \
  OPERATORS/op-bm-b.cc \
  OPERATORS/op-bm-bm.cc \
  OPERATORS/op-bm-sbm.cc \
  OPERATORS/op-cdm-cdm.cc \
  OPERATORS/op-cdm-cm.cc \
  OPERATORS/op-cdm-cs.cc \
  OPERATORS/op-cdm-dm.cc \
  OPERATORS/op-cdm-m.cc \
  OPERATORS/op-cdm-s.cc \
  OPERATORS/op-cell.cc \
  OPERATORS/op-chm.cc \
  OPERATORS/op-class.cc \
  OPERATORS/op-cm-cdm.cc \
  OPERATORS/op-cm-cm.cc \
  OPERATORS/op-cm-cs.cc \
  OPERATORS/op-cm-dm.cc \
  OPERATORS/op-cm-m.cc \
  OPERATORS/op-cm-pm.cc \
  OPERATORS/op-cm-s.cc \
  OPERATORS/op-cm-scm.cc \
  OPERATORS/op-cm-sm.cc \
  OPERATORS/op-cs-cm.cc \
  OPERATORS/op-cs-cs.cc \
  OPERATORS/op-cs-m.cc \
  OPERATORS/op-cs-s.cc \
  OPERATORS/op-cs-scm.cc \
  OPERATORS/op-cs-sm.cc \
  OPERATORS/op-dm-cdm.cc \
  OPERATORS/op-dm-cm.cc \
  OPERATORS/op-dm-cs.cc \
  OPERATORS/op-dm-dm.cc \
  OPERATORS/op-dm-m.cc \
  OPERATORS/op-dm-s.cc \
  OPERATORS/op-dm-scm.cc \
  OPERATORS/op-dm-sm.cc \
  OPERATORS/op-double-conv.cc \
  OPERATORS/op-fcdm-fcdm.cc \
  OPERATORS/op-fcdm-fcm.cc \
  OPERATORS/op-fcdm-fcs.cc \
  OPERATORS/op-fcdm-fdm.cc \
  OPERATORS/op-fcdm-fm.cc \
  OPERATORS/op-fcdm-fs.cc \
  OPERATORS/op-fcm-fcdm.cc \
  OPERATORS/op-fcm-fcm.cc \
  OPERATORS/op-fcm-fcs.cc \
  OPERATORS/op-fcm-fdm.cc \
  OPERATORS/op-fcm-fm.cc \
  OPERATORS/op-fcm-fs.cc \
  OPERATORS/op-fcm-pm.cc \
  OPERATORS/op-fcn.cc \
  OPERATORS/op-fcs-fcm.cc \
  OPERATORS/op-fcs-fcs.cc \
  OPERATORS/op-fcs-fm.cc \
  OPERATORS/op-fcs-fs.cc \
  OPERATORS/op-fdm-fcdm.cc \
  OPERATORS/op-fdm-fcm.cc \
  OPERATORS/op-fdm-fcs.cc \
  OPERATORS/op-fdm-fdm.cc \
  OPERATORS/op-fdm-fm.cc \
  OPERATORS/op-fdm-fs.cc \
  OPERATORS/op-float-conv.cc \
  OPERATORS/op-fm-fcdm.cc \
  OPERATORS/op-fm-fcm.cc \
  OPERATORS/op-fm-fcs.cc \
  OPERATORS/op-fm-fdm.cc \
  OPERATORS/op-fm-fm.cc \
  OPERATORS/op-fm-fs.cc \
  OPERATORS/op-fm-pm.cc \
  OPERATORS/op-fs-fcm.cc \
  OPERATORS/op-fs-fcs.cc \
  OPERATORS/op-fs-fm.cc \
  OPERATORS/op-fs-fs.cc \
  OPERATORS/op-i16-i16.cc \
  OPERATORS/op-i32-i32.cc \
  OPERATORS/op-i64-i64.cc \
  OPERATORS/op-i8-i8.cc \
  OPERATORS/op-int-concat.cc \
  OPERATORS/op-int-conv.cc \
  OPERATORS/op-m-cdm.cc \
  OPERATORS/op-m-cm.cc \
  OPERATORS/op-m-cs.cc \
  OPERATORS/op-m-dm.cc \
  OPERATORS/op-m-m.cc \
  OPERATORS/op-m-pm.cc \
  OPERATORS/op-m-s.cc \
  OPERATORS/op-m-scm.cc \
  OPERATORS/op-m-sm.cc \
  OPERATORS/op-pm-cm.cc \
  OPERATORS/op-pm-fcm.cc \
  OPERATORS/op-pm-fm.cc \
  OPERATORS/op-pm-m.cc \
  OPERATORS/op-pm-pm.cc \
  OPERATORS/op-pm-scm.cc \
  OPERATORS/op-pm-sm.cc \
  OPERATORS/op-range.cc \
  OPERATORS/op-s-cm.cc \
  OPERATORS/op-s-cs.cc \
  OPERATORS/op-s-m.cc \
  OPERATORS/op-s-s.cc \
  OPERATORS/op-s-scm.cc \
  OPERATORS/op-s-sm.cc \
  OPERATORS/op-sbm-b.cc \
  OPERATORS/op-sbm-bm.cc \
  OPERATORS/op-sbm-sbm.cc \
  OPERATORS/op-scm-cm.cc \
  OPERATORS/op-scm-cs.cc \
  OPERATORS/op-scm-m.cc \
  OPERATORS/op-scm-s.cc \
  OPERATORS/op-scm-scm.cc \
  OPERATORS/op-scm-sm.cc \
  OPERATORS/op-sm-cm.cc \
  OPERATORS/op-sm-cs.cc \
  OPERATORS/op-sm-m.cc \
  OPERATORS/op-sm-s.cc \
  OPERATORS/op-sm-scm.cc \
  OPERATORS/op-sm-sm.cc \
  OPERATORS/op-str-m.cc \
  OPERATORS/op-str-s.cc \
  OPERATORS/op-str-str.cc \
  OPERATORS/op-struct.cc \
  OPERATORS/op-ui16-ui16.cc \
  OPERATORS/op-ui32-ui32.cc \
  OPERATORS/op-ui64-ui64.cc \
  OPERATORS/op-ui8-ui8.cc

octinclude_HEADERS += \
  OPERATORS/op-dm-template.cc \
  OPERATORS/op-dms-template.cc \
  OPERATORS/op-int.h \
  OPERATORS/op-pm-template.cc
