CONFIG += release

QMAKE_CXXFLAGS += -MP
LIBDIR_SUFFIX = release

msvc-debug {
	QMAKE_CXXFLAGS_RELEASE += -Zi
	QMAKE_CXXFLAGS_RELEASE -= -O2
	QMAKE_LFLAGS_RELEASE += -debug
	QMAKE_CLEAN += $(DESTDIR)$(QMAKE_TARGET).pdb
}
