#!/bin/sh
#
# Wrapper for octave for binary installations that can't install
# octave in /usr/local/bin.
#
# The real binary should be installed in as octave.bin, and this file
# should be installed in the same directory as octave.

if test -n "$LD_LIBRARY_PATH"; then
  LD_LIBRARY_PATH="@LD_LIBRARY_PATH@:$LD_LIBRARY_PATH"
else
  LD_LIBRARY_PATH="@LD_LIBRARY_PATH@"
fi
export LD_LIBRARY_PATH

OCTAVE_HOME=@OCTAVE_HOME@
export OCTAVE_HOME

exec $OCTAVE_HOME/bin/octave.bin $*
