CRUFT_SOURCES += \
  liboctave/cruft/daspk/datv.f \
  liboctave/cruft/daspk/dcnst0.f \
  liboctave/cruft/daspk/dcnstr.f \
  liboctave/cruft/daspk/ddasic.f \
  liboctave/cruft/daspk/ddasid.f \
  liboctave/cruft/daspk/ddasik.f \
  liboctave/cruft/daspk/ddaspk.f \
  liboctave/cruft/daspk/ddstp.f \
  liboctave/cruft/daspk/ddwnrm.f \
  liboctave/cruft/daspk/dfnrmd.f \
  liboctave/cruft/daspk/dfnrmk.f \
  liboctave/cruft/daspk/dhels.f \
  liboctave/cruft/daspk/dheqr.f \
  liboctave/cruft/daspk/dinvwt.f \
  liboctave/cruft/daspk/dlinsd.f \
  liboctave/cruft/daspk/dlinsk.f \
  liboctave/cruft/daspk/dmatd.f \
  liboctave/cruft/daspk/dnedd.f \
  liboctave/cruft/daspk/dnedk.f \
  liboctave/cruft/daspk/dnsd.f \
  liboctave/cruft/daspk/dnsid.f \
  liboctave/cruft/daspk/dnsik.f \
  liboctave/cruft/daspk/dnsk.f \
  liboctave/cruft/daspk/dorth.f \
  liboctave/cruft/daspk/dslvd.f \
  liboctave/cruft/daspk/dslvk.f \
  liboctave/cruft/daspk/dspigm.f \
  liboctave/cruft/daspk/dyypnw.f
