## The following functions need to have tests written for them:

# nextpow2
# erfc
# erfinv
# lgamma
# cross
# commutation_matrix
# duplication_matrix

set test beta-1
set prog_output "ans = 1"
do_test beta-1.m

set test beta-2
set prog_output "error:.*"
do_test beta-2.m

set test beta-3
set prog_output "error:.*"
do_test beta-3.m

set test betai-1
set prog_output "ans = 1"
do_test betai-1.m

set test betai-2
set prog_output "error:.*"
do_test betai-2.m

set test betai-3
set prog_output "error:.*"
do_test betai-3.m

set test betai-4
set prog_output "error:.*"
do_test betai-4.m

set test ceil-1
set prog_output "ans = 1"
do_test ceil-1.m

set test ceil-2
set prog_output "ans = 1"
do_test ceil-2.m

set test ceil-3
set prog_output "error:.*"
do_test ceil-3.m

set test ceil-4
set prog_output "error:.*"
do_test ceil-4.m

set test erf-1
set prog_output "ans = 1"
do_test erf-1.m

set test erf-2
set prog_output "error:.*"
do_test erf-2.m

set test erf-3
set prog_output "error:.*"
do_test erf-3.m

set test exp-1
set prog_output "ans = 1"
do_test exp-1.m

set test exp-2
set prog_output "ans = 1"
do_test exp-2.m

set test exp-3
set prog_output "error:.*"
do_test exp-3.m

set test exp-4
set prog_output "error:.*"
do_test exp-4.m

set test fix-1
set prog_output "ans = 1"
do_test fix-1.m

set test fix-2
set prog_output "ans = 1"
do_test fix-2.m

set test fix-3
set prog_output "error:.*"
do_test fix-3.m

set test fix-4
set prog_output "error:.*"
do_test fix-4.m

set test floor-1
set prog_output "ans = 1"
do_test floor-1.m

set test floor-2
set prog_output "ans = 1"
do_test floor-2.m

set test floor-3
set prog_output "error:.*"
do_test floor-3.m

set test floor-4
set prog_output "error:.*"
do_test floor-4.m

set test gamma-1
set prog_output "ans = 1"
do_test gamma-1.m

set test gamma-2
set prog_output "error:.*"
do_test gamma-2.m

set test gamma-3
set prog_output "error:.*"
do_test gamma-3.m

set test gammai-1
set prog_output "ans = 1"
do_test gammai-1.m

set test gcd-1
set prog_output "ans = 1"
do_test gcd-1.m

set test gcd-2
set prog_output "usage:.*"
do_test gcd-2.m

set test gcd-3
set prog_output "error:.*"
do_test gcd-3.m

set test lcm-1
set prog_output "ans = 1"
do_test lcm-1.m

set test lcm-2
set prog_output "usage:.*"
do_test lcm-2.m

set test lcm-3
set prog_output "error:.*"
do_test lcm-3.m

set test max-1
set prog_output "ans = 1"
do_test max-1.m

set test max-2
set prog_output "ans = 1"
do_test max-2.m

set test max-3
set prog_output "\n... max:.*"
do_test max-3.m

set test max-4
set prog_output "\n... max:.*"
do_test max-4.m

set test min-1
set prog_output "ans = 1"
do_test min-1.m

set test min-2
set prog_output "ans = 1"
do_test min-2.m

set test min-3
set prog_output "\n... min:.*"
do_test min-3.m

set test min-4
set prog_output "\n... min:.*"
do_test min-4.m

set test pow2-1
set prog_output "ans = 1"
do_test pow2-1.m

set test pow2-2
set prog_output "ans = 1"
do_test pow2-2.m

set test pow2-3
set prog_output "error:.*"
do_test pow2-3.m

set test rem-1
set prog_output "ans = 1"
do_test rem-1.m

set test rem-2
set prog_output "ans = 1"
do_test rem-2.m

set test rem-3
set prog_output "usage:.*"
do_test rem-3.m

set test rem-4
set prog_output "usage:.*"
do_test rem-4.m

set test rem-5
set prog_output "error:.*"
do_test rem-5.m

set test rem-6
set prog_output "error:.*"
do_test rem-6.m

set test round-1
set prog_output "ans = 1"
do_test round-1.m

set test round-2
set prog_output "ans = 1"
do_test round-2.m

set test round-3
set prog_output "error:.*"
do_test round-3.m

set test round-4
set prog_output "error:.*"
do_test round-4.m

set test sign-1
set prog_output "ans = 1"
do_test sign-1.m

set test sign-2
set prog_output "ans = 1"
do_test sign-2.m

set test sign-3
set prog_output "error:.*"
do_test sign-3.m

set test sign-4
set prog_output "error:.*"
do_test sign-4.m

set test sqrt-1
set prog_output "ans = 1"
do_test sqrt-1.m

set test sqrt-2
set prog_output "ans = 1"
do_test sqrt-2.m

set test sqrt-3
set prog_output "error:.*"
do_test sqrt-3.m

set test sqrt-4
set prog_output "error:.*"
do_test sqrt-4.m

set test abs-1
set prog_output "ans = 1"
do_test abs-1.m

set test abs-2
set prog_output "ans = 1"
do_test abs-2.m

set test abs-3
set prog_output "error:.*"
do_test abs-3.m

set test abs-4
set prog_output "error:.*"
do_test abs-4.m

set test xor-1
set prog_output "ans = 1"
do_test xor-1.m

set test xor-2
set prog_output "ans = 1"
do_test xor-2.m

set test xor-3
set prog_output "error:.*"
do_test xor-3.m

set test xor-4
set prog_output "error:.*"
do_test xor-4.m

set test arg-1
set prog_output "ans = 1"
do_test arg-1.m

set test arg-2
set prog_output "ans = 1"
do_test arg-2.m

set test arg-3
set prog_output "error:.*"
do_test arg-3.m

set test arg-4
set prog_output "error:.*"
do_test arg-4.m

set test conj-1
set prog_output "ans = 1"
do_test conj-1.m

set test conj-2
set prog_output "ans = 1"
do_test conj-2.m

set test conj-3
set prog_output "error:.*"
do_test conj-3.m

set test conj-4
set prog_output "error:.*"
do_test conj-4.m

set test imag-1
set prog_output "ans = 1"
do_test imag-1.m

set test imag-2
set prog_output "ans = 1"
do_test imag-2.m

set test imag-3
set prog_output "error:.*"
do_test imag-3.m

set test imag-4
set prog_output "error:.*"
do_test imag-4.m

set test real-1
set prog_output "ans = 1"
do_test real-1.m

set test real-2
set prog_output "ans = 1"
do_test real-2.m

set test real-3
set prog_output "error:.*"
do_test real-3.m

set test real-4
set prog_output "error:.*"
do_test real-4.m

set test log-1
set prog_output "ans = 1"
do_test log-1.m

set test log-2
set prog_output "error:.*"
do_test log-2.m

set test log-3
set prog_output "error:.*"
do_test log-3.m

set test log10-1
set prog_output "ans = 1"
do_test log10-1.m

set test log10-2
set prog_output "error:.*"
do_test log10-2.m

set test log10-3
set prog_output "error:.*"
do_test log10-3.m

set test log2-1
set prog_output "ans = 1"
do_test log2-1.m

set test log2-2
set prog_output "error:.*"
do_test log2-2.m

set test log2-3
set prog_output "error:.*"
do_test log2-3.m

set test sin-1
set prog_output "ans = 1"
do_test sin-1.m

set test sin-2
set prog_output "error:.*"
do_test sin-2.m

set test sin-3
set prog_output "error:.*"
do_test sin-3.m

set test cos-1
set prog_output "ans = 1"
do_test cos-1.m

set test cos-2
set prog_output "error:.*"
do_test cos-2.m

set test cos-3
set prog_output "error:.*"
do_test cos-3.m

set test tan-1
set prog_output "ans = 1"
do_test tan-1.m

set test tan-2
set prog_output "error:.*"
do_test tan-2.m

set test tan-3
set prog_output "error:.*"
do_test tan-3.m

set test sec-1
set prog_output "ans = 1"
do_test sec-1.m

set test sec-2
set prog_output "error:.*"
do_test sec-2.m

set test sec-3
set prog_output "error:.*"
do_test sec-3.m

set test csc-1
set prog_output "ans = 1"
do_test csc-1.m

set test csc-2
set prog_output "error:.*"
do_test csc-2.m

set test csc-3
set prog_output "error:.*"
do_test csc-3.m

set test cot-1
set prog_output "ans = 1"
do_test cot-1.m

set test cot-2
set prog_output "error:.*"
do_test cot-2.m

set test cot-3
set prog_output "error:.*"
do_test cot-3.m

set test asin-1
set prog_output "ans = 1"
do_test asin-1.m

set test asin-2
set prog_output "error:.*"
do_test asin-2.m

set test asin-3
set prog_output "error:.*"
do_test asin-3.m

set test acos-1
set prog_output "ans = 1"
do_test acos-1.m

set test acos-2
set prog_output "error:.*"
do_test acos-2.m

set test acos-3
set prog_output "error:.*"
do_test acos-3.m

set test atan-1
set prog_output "ans = 1"
do_test atan-1.m

set test atan-2
set prog_output "error:.*"
do_test atan-2.m

set test atan-3
set prog_output "error:.*"
do_test atan-3.m

set test asec-1
set prog_output "ans = 1"
do_test asec-1.m

set test asec-2
set prog_output "error:.*"
do_test asec-2.m

set test asec-3
set prog_output "error:.*"
do_test asec-3.m

set test acsc-1
set prog_output "ans = 1"
do_test acsc-1.m

set test acsc-2
set prog_output "error:.*"
do_test acsc-2.m

set test acsc-3
set prog_output "error:.*"
do_test acsc-3.m

set test acot-1
set prog_output "ans = 1"
do_test acot-1.m

set test acot-2
set prog_output "error:.*"
do_test acot-2.m

set test acot-3
set prog_output "error:.*"
do_test acot-3.m

set test sinh-1
set prog_output "ans = 1"
do_test sinh-1.m

set test sinh-2
set prog_output "error:.*"
do_test sinh-2.m

set test sinh-3
set prog_output "error:.*"
do_test sinh-3.m

set test cosh-1
set prog_output "ans = 1"
do_test cosh-1.m

set test cosh-2
set prog_output "error:.*"
do_test cosh-2.m

set test cosh-3
set prog_output "error:.*"
do_test cosh-3.m

set test tanh-1
set prog_output "ans = 1"
do_test tanh-1.m

set test tanh-2
set prog_output "error:.*"
do_test tanh-2.m

set test tanh-3
set prog_output "error:.*"
do_test tanh-3.m

set test sech-1
set prog_output "ans = 1"
do_test sech-1.m

set test sech-2
set prog_output "error:.*"
do_test sech-2.m

set test sech-3
set prog_output "error:.*"
do_test sech-3.m

set test csch-1
set prog_output "ans = 1"
do_test csch-1.m

set test csch-2
set prog_output "error:.*"
do_test csch-2.m

set test csch-3
set prog_output "error:.*"
do_test csch-3.m

set test coth-1
set prog_output "ans = 1"
do_test coth-1.m

set test coth-2
set prog_output "error:.*"
do_test coth-2.m

set test coth-3
set prog_output "error:.*"
do_test coth-3.m

set test asinh-1
set prog_output "ans = 1"
do_test asinh-1.m

set test asinh-2
set prog_output "error:.*"
do_test asinh-2.m

set test asinh-3
set prog_output "error:.*"
do_test asinh-3.m

set test acosh-1
set prog_output "ans = 1"
do_test acosh-1.m

set test acosh-2
set prog_output "error:.*"
do_test acosh-2.m

set test acosh-3
set prog_output "error:.*"
do_test acosh-3.m

set test atanh-1
set prog_output "ans = 1"
do_test atanh-1.m

set test atanh-2
set prog_output "error:.*"
do_test atanh-2.m

set test atanh-3
set prog_output "error:.*"
do_test atanh-3.m

set test asech-1
set prog_output "ans = 1"
do_test asech-1.m

set test asech-2
set prog_output "error:.*"
do_test asech-2.m

set test asech-3
set prog_output "error:.*"
do_test asech-3.m

set test acsch-1
set prog_output "ans = 1"
do_test acsch-1.m

set test acsch-2
set prog_output "error:.*"
do_test acsch-2.m

set test acsch-3
set prog_output "error:.*"
do_test acsch-3.m

set test acoth-1
set prog_output "ans = 1"
do_test acoth-1.m

set test acoth-2
set prog_output "error:.*"
do_test acoth-2.m

set test acoth-3
set prog_output "error:.*"
do_test acoth-3.m

set test atan2-1
set prog_output "ans = 1"
do_test atan2-1.m

set test atan2-2
set prog_output "\n... atan2:.*"
do_test atan2-2.m

set test atan2-3
set prog_output "\n... atan2:.*"
do_test atan2-3.m

set test sum-1
set prog_output "ans = 1"
do_test sum-1.m

set test sum-2
set prog_output "ans = 1"
do_test sum-2.m

set test sum-3
set prog_output "\n... sum:.*"
do_test sum-3.m

set test sum-4
set prog_output "\n... sum:.*"
do_test sum-4.m

set test prod-1
set prog_output "ans = 1"
do_test prod-1.m

set test prod-2
set prog_output "ans = 1"
do_test prod-2.m

set test prod-3
set prog_output "\n... prod:.*"
do_test prod-3.m

set test prod-4
set prog_output "\n... prod:.*"
do_test prod-4.m

set test cumsum-1
set prog_output "ans = 1"
do_test cumsum-1.m

set test cumsum-2
set prog_output "ans = 1"
do_test cumsum-2.m

set test cumsum-3
set prog_output "\n... cumsum:.*"
do_test cumsum-3.m

set test cumsum-4
set prog_output "\n... cumsum:.*"
do_test cumsum-4.m

set test cumprod-1
set prog_output "ans = 1"
do_test cumprod-1.m

set test cumprod-2
set prog_output "ans = 1"
do_test cumprod-2.m

set test cumprod-3
set prog_output "\n... cumprod:.*"
do_test cumprod-3.m

set test cumprod-4
set prog_output "\n... cumprod:.*"
do_test cumprod-4.m

set test sumsq-1
set prog_output "ans = 1"
do_test sumsq-1.m

set test sumsq-2
set prog_output "ans = 1"
do_test sumsq-2.m

set test sumsq-3
set prog_output "\n... sumsq:.*"
do_test sumsq-3.m

set test sumsq-4
set prog_output "\n... sumsq:.*"
do_test sumsq-4.m

set test bincoeff-1
set prog_output "ans = 1"
do_test bincoeff-1.m

set test bincoeff-2
set prog_output "usage:.*"
do_test bincoeff-2.m

set test bincoeff-3
set prog_output "usage.*"
do_test bincoeff-3.m
