classes_FCN_FILES = \
  @Blork/Blork.m \
  @Blork/bleek.m \
  @Blork/display.m \
  @Blork/get.m \
  @Blork/set.m \
  @Cork/Cork.m \
  @Cork/click.m \
  @Cork/display.m \
  @Cork/get.m \
  @Cork/set.m \
  @Dork/Dork.m \
  @Dork/bling.m \
  @Dork/display.m \
  @Dork/gack.m \
  @Dork/get.m \
  @Dork/getStash.m \
  @Dork/private/myStash.m \
  @Dork/set.m \
  @Gork/Gork.m \
  @Gork/cork.m \
  @Gork/display.m \
  @Gork/gark.m \
  @Gork/get.m \
  @Gork/set.m \
  @Gork/subsasgn.m \
  @Gork/subsref.m \
  @Pork/Pork.m \
  @Pork/bling.m \
  @Pork/display.m \
  @Pork/get.m \
  @Pork/gurk.m \
  @Pork/private/myStash.m \
  @Pork/set.m \
  @Sneetch/Sneetch.m \
  @Sneetch/display.m \
  @Snork/Snork.m \
  @Snork/cack.m \
  @Snork/display.m \
  @Snork/end.m \
  @Snork/get.m \
  @Snork/getStash.m \
  @Snork/gick.m \
  @Snork/loadobj.m \
  @Snork/private/myStash.m \
  @Snork/saveobj.m \
  @Snork/set.m \
  @Snork/subsasgn.m \
  @Snork/subsindex.m \
  @Snork/subsref.m \
  @Spork/Spork.m \
  @Spork/cack.m \
  @Spork/display.m \
  @Spork/geek.m \
  @Spork/get.m \
  @Spork/getStash.m \
  @Spork/loadobj.m \
  @Spork/private/myStash.m \
  @Spork/saveobj.m \
  @Spork/set.m \
  test_classes.m

FCN_FILES += $(classes_FCN_FILES)
