classes_FCN_FILES = \
  classes/@Blork/Blork.m \
  classes/@Blork/bleek.m \
  classes/@Blork/display.m \
  classes/@Blork/get.m \
  classes/@Blork/set.m \
  classes/foo_payment.m \
  classes/@Cork/Cork.m \
  classes/@Cork/click.m \
  classes/@Cork/display.m \
  classes/@Cork/get.m \
  classes/@Cork/set.m \
  classes/@Dork/Dork.m \
  classes/@Dork/bling.m \
  classes/@Dork/display.m \
  classes/@Dork/gack.m \
  classes/@Dork/get.m \
  classes/@Dork/getStash.m \
  classes/@Dork/private/myStash.m \
  classes/@Dork/set.m \
  classes/@Gork/Gork.m \
  classes/@Gork/cork.m \
  classes/@Gork/display.m \
  classes/@Gork/gark.m \
  classes/@Gork/get.m \
  classes/@Gork/set.m \
  classes/@Gork/subsasgn.m \
  classes/@Gork/subsref.m \
  classes/@Pork/Pork.m \
  classes/@Pork/bling.m \
  classes/@Pork/display.m \
  classes/@Pork/get.m \
  classes/@Pork/gurk.m \
  classes/@Pork/private/myStash.m \
  classes/@Pork/set.m \
  classes/@Sneetch/Sneetch.m \
  classes/@Sneetch/display.m \
  classes/@Snork/Snork.m \
  classes/@Snork/cack.m \
  classes/@Snork/display.m \
  classes/@Snork/end.m \
  classes/@Snork/get.m \
  classes/@Snork/getStash.m \
  classes/@Snork/gick.m \
  classes/@Snork/loadobj.m \
  classes/@Snork/private/myStash.m \
  classes/@Snork/saveobj.m \
  classes/@Snork/set.m \
  classes/@Snork/subsasgn.m \
  classes/@Snork/subsindex.m \
  classes/@Snork/subsref.m \
  classes/@Spork/Spork.m \
  classes/@Spork/cack.m \
  classes/@Spork/display.m \
  classes/@Spork/geek.m \
  classes/@Spork/get.m \
  classes/@Spork/getStash.m \
  classes/@Spork/loadobj.m \
  classes/@Spork/private/myStash.m \
  classes/@Spork/saveobj.m \
  classes/@Spork/set.m \
  classes/test_classes.m

FCN_FILES += $(classes_FCN_FILES)
