## The following functions need to have tests written for them:

# detrend

set test detrend-1
set prog_output "ans = 1"
do_test detrend-1.m

set test detrend-2
set prog_output "ans = 1"
do_test detrend-2.m

set test detrend-3
set prog_output "ans = 1"
do_test detrend-3.m

# fft

set test fft-1
set prog_output "ans = 1"
do_test fft-1.m

# ifft

set test ifft-1
set prog_output "ans = 1"
do_test ifft-1.m

# fft2

set test fft2-1
set prog_output "ans = 1"
do_test fft2-1.m

# ifft2

set test ifft2-1
set prog_output "ans = 1"
do_test ifft2-1.m

# fftconv
# fftfilt
# filter
# freqz
# sinc
