set test fieldnames-1
set prog_output "^ans = 1"
do_test fieldnames-1.m

set test fieldnames-2
set prog_output "^ans = 1"
do_test fieldnames-2.m

set test fieldnames-3
set prog_output "\n... fieldnames:.*"
do_test fieldnames-3.m

set test fieldnames-4
set prog_output "\n... fieldnames:.*"
do_test fieldnames-4.m

set test fieldnames-5
set prog_output "^error:.*"
do_test fieldnames-5.m

set test isfield-1
set prog_output "^ans = 1"
do_test isfield-1.m

set test isfield-2
set prog_output "^ans = 0"
do_test isfield-2.m

set test isfield-3
set prog_output "\n... isfield:.*"
do_test isfield-3.m

set test isfield-4
set prog_output "\n... isfield:.*"
do_test isfield-4.m

set test isfield-5
set prog_output "^ans = 1"
do_test isfield-5.m

set test isfield-6
set prog_output "^ans = 1"
do_test isfield-6.m

set test isstruct-1
set prog_output "^ans = 0"
do_test isstruct-1.m

set test isstruct-2
set prog_output "^ans = 0"
do_test isstruct-2.m

set test isstruct-3
set prog_output "^ans = 0"
do_test isstruct-3.m

set test isstruct-4
set prog_output "^ans = 0"
do_test isstruct-4.m

set test isstruct-5
set prog_output "^ans = 0"
do_test isstruct-5.m

set test isstruct-6
set prog_output "^ans = 0"
do_test isstruct-6.m

set test isstruct-7
set prog_output "^ans = 0"
do_test isstruct-7.m

set test isstruct-8
set prog_output "^ans = 1"
do_test isstruct-8.m

set test isstruct-9
set prog_output "^ans = 1"
do_test isstruct-9.m

set test isstruct-10
set prog_output "\n... isstruct:.*"
do_test isstruct-10.m

set test isstruct-11
set prog_output "\n... isstruct:.*"
do_test isstruct-11.m
