win32-msvc* {
	CONFIG += release warn_off
	QMAKE_CXXFLAGS += -MP
	QMAKE_CXXFLAGS_RELEASE += -Zi
	QMAKE_CXXFLAGS_RELEASE -= -O2
	QMAKE_LFLAGS_RELEASE += -debug
	QMAKE_CLEAN += $(DESTDIR)$(QMAKE_TARGET).pdb
}
