# balance
# cond

set test det-1
set prog_output "ans = 1"
do_test det-1.m

set test det-2
set prog_output "\n... det:.*"
do_test det-2.m

set test det-3
set prog_output "\n... det:.*"
do_test det-3.m

set test det-4
set prog_output "error:.*"
do_test det-4.m

set test eig-1
set prog_output "ans = 1"
do_test eig-1.m

set test eig-2
set prog_output "ans = 1"
do_test eig-2.m

set test eig-3
set prog_output "\n... eig:.*"
do_test eig-3.m

set test eig-4
set prog_output "\n... eig:.*"
do_test eig-4.m

set test eig-5
set prog_output "error:.*"
do_test eig-5.m

# givens

set test inv-1
set prog_output "ans = 1"
do_test inv-1.m

set test inv-2
set prog_output "\n... inv:.*"
do_test inv-2.m

set test inv-3
set prog_output "\n... inv:.*"
do_test inv-3.m

set test inv-4
set prog_output "error:.*"
do_test inv-4.m

# norm
# null
# orth
# pinv
# rank
# trace
# chol
# hess

set test lu-1
set prog_output "ans = 1"
do_test lu-1.m

set test lu-2
set prog_output "ans = 1"
do_test lu-2.m

set test lu-3
set prog_output "ans = 1"
do_test lu-3.m

set test lu-4
set prog_output "\n... lu:.*"
do_test lu-4.m

set test lu-5
set prog_output "\n... lu:.*"
do_test lu-5.m

set test lu-6
set prog_output "error:.*"
do_test lu-6.m

set test qr-1
set prog_output "ans = 1"
do_test qr-1.m

set test qr-2
set prog_output "ans = 1"
do_test qr-2.m

set test qr-3
set prog_output "ans = 1"
do_test qr-3.m

set test qr-4
set prog_output "ans = 1"
do_test qr-4.m

set test qr-5
set prog_output "\n... qr:.*"
do_test qr-5.m

set test qr-6
set prog_output "\n... qr:.*"
do_test qr-6.m

# schur

set test svd-1
set prog_output "ans = 1"
do_test svd-1.m

set test svd-2
set prog_output "ans = 1"
do_test svd-2.m

set test svd-3
set prog_output "ans = 1"
do_test svd-3.m

set test svd-4
set prog_output "ans = 1"
do_test svd-4.m

set test svd-5
set prog_output "ans = 1"
do_test svd-5.m

set test svd-6
set prog_output "ans = 1"
do_test svd-6.m

set test svd-7
set prog_output "\n... svd:.*"
do_test svd-7.m

set test svd-8
set prog_output "\n... svd:.*"
do_test svd-8.m

set test svd-9
set prog_output "\n... svd:.*"
do_test svd-9.m

# expm
# logm
# sqrtm
# kron
# qzhess
# qzval
# syl
