## The following functions need to have tests written for them:

# balance
# givens
# norm
# null
# orth
# pinv
# rank
# logm
# sqrtm
# kron
# qzhess
# qzval

set test cond-1
set prog_output "^ans = 1"
do_test cond-1.m

set test cond-2
set prog_output "^ans = 1"
do_test cond-2.m

set test cond-3
set prog_output "^usage:.*"
do_test cond-3.m

set test cond-4
set prog_output "^usage:.*"
do_test cond-4.m

set test det-1
set prog_output "^ans = 1"
do_test det-1.m

set test det-2
set prog_output "\n... det:.*"
do_test det-2.m

set test det-3
set prog_output "\n... det:.*"
do_test det-3.m

set test det-4
set prog_output "^error:.*"
do_test det-4.m

set test eig-1
set prog_output "^ans = 1"
do_test eig-1.m

set test eig-2
set prog_output "^ans = 1"
do_test eig-2.m

set test eig-3
set prog_output "\n... eig:.*"
do_test eig-3.m

set test eig-4
set prog_output "\n... eig:.*"
do_test eig-4.m

set test eig-5
set prog_output "^error:.*"
do_test eig-5.m

set test expm-1
set prog_output "^ans = 1"
do_test expm-1.m

set test expm-2
set prog_output "^ans = 1"
do_test expm-2.m

set test expm-3
set prog_output "^ans = 1"
do_test expm-3.m

set test expm-4
set prog_output "^\n... expm:.*"
do_test expm-4.m

set test expm-5
set prog_output "^\n... expm:.*"
do_test expm-5.m

set test expm-6
set prog_output "^error:.*"
do_test expm-6.m

set test inv-1
set prog_output "^ans = 1"
do_test inv-1.m

set test inv-2
set prog_output "\n... inv:.*"
do_test inv-2.m

set test inv-3
set prog_output "\n... inv:.*"
do_test inv-3.m

set test inv-4
set prog_output "^error:.*"
do_test inv-4.m

set test trace-1
set prog_output "^ans = 1"
do_test trace-1.m

set test trace-2
set prog_output "^ans = 1"
do_test trace-2.m

set test trace-3
set prog_output "^ans = 1"
do_test trace-3.m

set test trace-4
set prog_output "^usage:.*"
do_test trace-4.m

set test trace-5
set prog_output "^usage:.*"
do_test trace-5.m

set test chol-1
set prog_output "^ans = 1"
do_test chol-1.m

set test chol-2
set prog_output "^error:.*"
do_test chol-2.m

set test chol-3
set prog_output "^error:.*"
do_test chol-3.m

set test chol-4
set prog_output "\n... chol:.*"
do_test chol-4.m

set test chol-5
set prog_output "\n... chol:.*"
do_test chol-5.m

set test hess-1
set prog_output "^ans = 1"
do_test hess-1.m

set test hess-2
set prog_output "\n... hess:.*"
do_test hess-2.m

set test hess-3
set prog_output "\n... hess:.*"
do_test hess-3.m

set test hess-4
set prog_output "^error:.*"
do_test hess-4.m

set test lu-1
set prog_output "^ans = 1"
do_test lu-1.m

set test lu-2
set prog_output "^ans = 1"
do_test lu-2.m

set test lu-3
set prog_output "^ans = 1"
do_test lu-3.m

set test lu-4
set prog_output "\n... lu:.*"
do_test lu-4.m

set test lu-5
set prog_output "\n... lu:.*"
do_test lu-5.m

set test lu-6
set prog_output "^ans = 1"
do_test lu-6.m

set test qr-1
set prog_output "^ans = 1"
do_test qr-1.m

set test qr-2
set prog_output "^ans = 1"
do_test qr-2.m

set test qr-3
set prog_output "^ans = 1"
do_test qr-3.m

set test qr-4
set prog_output "^ans = 1"
do_test qr-4.m

set test qr-5
set prog_output "\n... qr:.*"
do_test qr-5.m

set test qr-6
set prog_output "\n... qr:.*"
do_test qr-6.m

set test qr-7
set prog_output "^ans = 1";
do_test qr-7.m

set test schur-1
set prog_output "^ans = 1"
do_test schur-1.m

set test schur-2
set prog_output "\n... schur:.*"
do_test schur-2.m

set test schur-3
set prog_output "^warning:.*"
do_test schur-3.m

set test schur-4
set prog_output "^error:.*"
do_test schur-4.m

set test svd-1
set prog_output "^ans = 1"
do_test svd-1.m

set test svd-2
set prog_output "^ans = 1"
do_test svd-2.m

set test svd-3
set prog_output "^ans = 1"
do_test svd-3.m

set test svd-4
set prog_output "^ans = 1"
do_test svd-4.m

set test svd-5
set prog_output "^ans = 1"
do_test svd-5.m

set test svd-6
set prog_output "^ans = 1"
do_test svd-6.m

set test svd-7
set prog_output "\n... svd:.*"
do_test svd-7.m

set test svd-8
set prog_output "\n... svd:.*"
do_test svd-8.m

set test svd-9
set prog_output "\n... svd:.*"
do_test svd-9.m

set test syl-1
set prog_output "^ans = 1"
do_test syl-1.m

set test syl-2
set prog_output "\n... syl:.*"
do_test syl-2.m

set test syl-3
set prog_output "\n... syl:.*"
do_test syl-3.m

set test syl-4
set prog_output "^error:.*"
do_test syl-4.m
