set test global-1
set prog_output "G = 1"
do_test global-1.m

set test global-2
set prog_output "G = 1"
do_test global-2.m

set test global-3
set prog_output "error:.*"
do_test global-3.m

set test global-4
set prog_output "^$"
do_test global-4.m

set test global-5
set prog_output "error:.*"
do_test global-5.m

set test global-6
set prog_output "H = 1"
do_test global-6.m

set test global-7
set prog_output "error:.*"
do_test global-7.m

set test global-8
set prog_output "H = 1"
do_test global-8.m
