set test switch-1
set prog_output "^ans = 1"
do_test switch-1.m

set test switch-2
set prog_output "^ans = 1"
do_test switch-2.m

set test switch-3
set prog_output "^ans = 1"
do_test switch-3.m

set test switch-4
set prog_output "parse error.*"
do_test switch-4.m

set test switch-5
set prog_output "parse error.*"
do_test switch-5.m

set test switch-6
set prog_output "parse error.*"
do_test switch-6.m
