set test contin-1
set prog_output "parse error.*"
do_test contin-1.m

set test contin-2
set prog_output "ans = 1"
do_test contin-2.m

set test contin-3
set prog_output "ans = 1"
do_test contin-3.m

set test contin-4
set prog_output "parse error.*"
do_test contin-4.m

set test contin-5
set prog_output "ans = 1"
do_test contin-5.m

set test contin-6
set prog_output "ans = 1"
do_test contin-6.m

set test contin-7
set prog_output "ans = 1"
do_test contin-7.m

set test contin-8
set prog_output "ans = 1"
do_test contin-8.m

set test contin-9
set prog_output "ans = 1"
do_test contin-9.m

set test contin-10
set prog_output "ans = 6"
do_test contin-10.m

set test contin-11
set prog_output "ans = 1"
do_test contin-11.m

set test contin-12
set prog_output "ans = 1"
do_test contin-12.m

set test contin-13
set prog_output "ans = 1"
do_test contin-13.m

set test contin-14
set prog_output "ans = 1"
do_test contin-14.m

set test contin-15
set prog_output "ans = 1"
do_test contin-15.m

set test contin-16
set prog_output "ans = 1"
do_test contin-16.m
