      SUBROUTINE CONDVC( N, X, LENX, INCX, XMAX, XMIN )
C
      INTEGER            N, LENX, INCX
      DOUBLE PRECISION   XMAX, XMIN
      DOUBLE PRECISION   X(LENX)
C
      DOUBLE PRECISION   WMACH
      COMMON    /SOLMCH/ WMACH(15)
C
C  CONDVC  FINDS THE BIGGEST AND SMALLEST COMPONENTS OF N ELEMENTS OF X.
C
      INTEGER            I, IX
      DOUBLE PRECISION   DABS, DMAX1, DMIN1
C
      XMAX = 0.0D+0
      XMIN = WMACH(8)
      IF (N .LT. 1) RETURN
      IX   = 1
      DO 100 I = 1, N
         XMAX = DMAX1( XMAX, DABS(X(IX)) )
         XMIN = DMIN1( XMIN, DABS(X(IX)) )
         IX   = IX + INCX
  100 CONTINUE
      RETURN
C
C  END OF CONDVC
      END
