      SUBROUTINE COPYMX( NROWS, N, IROWX, X, LROWX, IROWY, Y, LROWY )
C
      INTEGER            NROWS, N, IROWX, LROWX, IROWY, LROWY
      DOUBLE PRECISION   X(LROWX,N), Y(LROWY,N)
C
C  LOAD  NROWS  FROM THE MATRIX  X  INTO THE MATRIX  Y.
C  THE ROWS CONCERNED ARE ROWS  IROWX, IROWX+1,...  OF  X  AND ROWS
C  IROWY, IROWY+1,...  OF THE ARRAY  Y.
C
      INTEGER            J
      DO 100 J = 1, N
         CALL COPYVC( NROWS, X(IROWX,J), NROWS, 1, Y(IROWY,J), NROWS, 1)
  100 CONTINUE
C
      RETURN
C
C  END OF COPYMX
      END
