set test create_set-1
set prog_output "^ans = 1"
do_test create_set-1.m

set test create_set-2
set prog_output "^ans = 1"
do_test create_set-2.m

set test create_set-3
set prog_output "^ans = 1"
do_test create_set-3.m

set test create_set-4
set prog_output "^usage:.*"
do_test create_set-4.m

set test union-1
set prog_output "^ans = 1"
do_test union-1.m

set test union-2
set prog_output "^ans = 1"
do_test union-2.m

set test union-3
set prog_output "^ans = 1"
do_test union-3.m

set test union-4
set prog_output "^usage:.*"
do_test union-4.m

set test union-5
set prog_output "^usage:.*"
do_test union-5.m

set test intersection-1
set prog_output "^ans = 1"
do_test intersection-1.m

set test intersection-2
set prog_output "^ans = 1"
do_test intersection-2.m

set test intersection-3
set prog_output "^ans = 1"
do_test intersection-3.m

set test intersection-4
set prog_output "^usage:.*"
do_test intersection-4.m

set test intersection-5
set prog_output "^usage:.*"
do_test intersection-5.m

set test complement-1
set prog_output "^ans = 1"
do_test complement-1.m

set test complement-2
set prog_output "^ans = 1"
do_test complement-2.m

set test complement-3
set prog_output "^ans = 1"
do_test complement-3.m

set test complement-4
set prog_output "^usage:.*"
do_test complement-4.m

set test complement-5
set prog_output "^usage:.*"
do_test complement-5.m
