## The following functions need to have tests written for them:

# colloc

set test quad-1
set prog_output "ans = 1"
do_test quad-1.m

set test quad-2
set prog_output "ans = 1"
do_test quad-2.m

set test quad-3
set prog_output "\n... quad:.*"
do_test quad-3.m

set test quad-4
set prog_output "\n... quad:.*"
do_test quad-4.m

set test quad_options-1
set prog_output "ans = 1"
do_test quad_options-1.m

set test quad_options-2
set prog_output "\n... quad_options:.*"
do_test quad_options-2.m

set test quad_options-3
set prog_output "\n... quad_options:.*"
do_test quad_options-3.m
