# Generated automatically from Makefile.in by configure.
#
# Makefile for octave's libcruft/slatec-fn directory
#
# John W. Eaton
# jwe@bevo.che.wisc.edu
# University of Wisconsin-Madison
# Department of Chemical Engineering

TOPDIR = ../..

srcdir = .
top_srcdir = ../..

EXTERNAL_DISTFILES = $(DISTFILES)

include $(TOPDIR)/Makeconf

include ../Makerules
