EXTRA_DIST += blas/module.mk

BLAS_SRC = \
  blas/dasum.f \
  blas/daxpy.f \
  blas/dcabs1.f \
  blas/dcopy.f \
  blas/ddot.f \
  blas/dgemm.f \
  blas/dgemv.f \
  blas/dger.f \
  blas/dmach.f \
  blas/dnrm2.f \
  blas/drot.f \
  blas/dscal.f \
  blas/dswap.f \
  blas/dsymv.f \
  blas/dsyr.f \
  blas/dsymm.f \
  blas/dsyr2.f \
  blas/dsyr2k.f \
  blas/dsyrk.f \
  blas/dtbsv.f \
  blas/dtrmm.f \
  blas/dtrmv.f \
  blas/dtrsm.f \
  blas/dtrsv.f \
  blas/dzasum.f \
  blas/dznrm2.f \
  blas/icamax.f \
  blas/idamax.f \
  blas/isamax.f \
  blas/izamax.f \
  blas/lsame.f \
  blas/sdot.f \
  blas/sgemm.f \
  blas/sgemv.f \
  blas/sscal.f \
  blas/ssyrk.f \
  blas/strsm.f \
  blas/zaxpy.f \
  blas/zcopy.f \
  blas/zdotc.f \
  blas/zdotu.f \
  blas/zdrot.f \
  blas/zdscal.f \
  blas/zgemm.f \
  blas/zgemv.f \
  blas/zgerc.f \
  blas/zgeru.f \
  blas/zhemv.f \
  blas/zhemm.f \
  blas/zher.f \
  blas/zher2.f \
  blas/zher2k.f \
  blas/zherk.f \
  blas/zscal.f \
  blas/zswap.f \
  blas/zsyrk.f \
  blas/ztbsv.f \
  blas/ztrmm.f \
  blas/ztrmv.f \
  blas/ztrsm.f \
  blas/ztrsv.f \
  blas/sasum.f \
  blas/saxpy.f \
  blas/scabs1.f \
  blas/scopy.f \
  blas/sger.f \
  blas/smach.f \
  blas/snrm2.f \
  blas/srot.f \
  blas/sswap.f \
  blas/ssymv.f \
  blas/ssyr.f \
  blas/ssymm.f \
  blas/ssyr2.f \
  blas/ssyr2k.f \
  blas/stbsv.f \
  blas/strmm.f \
  blas/strmv.f \
  blas/strsv.f \
  blas/scasum.f \
  blas/scnrm2.f \
  blas/caxpy.f \
  blas/ccopy.f \
  blas/cdotc.f \
  blas/cdotu.f \
  blas/chemm.f \
  blas/csrot.f \
  blas/csscal.f \
  blas/cgemm.f \
  blas/cgemv.f \
  blas/cgerc.f \
  blas/cgeru.f \
  blas/chemv.f \
  blas/cher.f \
  blas/cher2.f \
  blas/cher2k.f \
  blas/cherk.f \
  blas/cscal.f \
  blas/cswap.f \
  blas/csyrk.f \
  blas/ctbsv.f \
  blas/ctrmm.f \
  blas/ctrmv.f \
  blas/ctrsm.f \
  blas/ctrsv.f

if AMCOND_HAVE_BLAS
  EXTRA_DIST += $(BLAS_SRC)
else
  libcruft_la_SOURCES += $(BLAS_SRC)
endif
