set test args-1
set prog_output "nargin: 0, nargout: 0"
do_test args-1.m

set test args-2
set prog_output "nargin: 1, nargout: 0"
do_test args-2.m

set test args-3
set prog_output "nargin: 0, nargout: 1"
do_test args-3.m

set test args-4
set prog_output "nargin: 1, nargout: 1"
do_test args-4.m

set test args-5
set prog_output "nargin: 0, nargout: 0"
do_test args-5.m

set test args-6
set prog_output "nargin: 1, nargout: 0"
do_test args-6.m

set test args-7
set prog_output "nargin: 0, nargout: 1"
do_test args-7.m

set test args-8
set prog_output "nargin: 1, nargout: 1"
do_test args-8.m

set test args-9
set prog_output "nargin: 4, nargout: 2"
do_test args-9.m

set test args-10
set prog_output "nargin: 3, nargout: 4"
do_test args-10.m
