######################################################################
# Automatically generated by qmake (2.01a) ven. juin 8 21:29:34 2007
######################################################################

TEMPLATE = lib
TARGET = qcodeedit
DESTDIR = ..
CONFIG += staticlib

DEPENDPATH += . document language widgets qnfa
INCLUDEPATH += . document language widgets qnfa

CONFIG += qnfa

QT += xml

UI_DIR = 
MOC_DIR = moc-dir
OBJECTS_DIR = objects.dir

# Input
include(lib.pri)
