## Tests with do_fortran_indexing == "false"

## scalar tests

set test index-s-1
set prog_output "ans = 1"
do_test s-1.m

set test index-s-2
set prog_output "ans = 1"
do_test s-2.m

set test index-s-3
set prog_output "ans = 1"
do_test s-3.m

set test index-s-4
set prog_output "ans = 1"
do_test s-4.m

set test index-s-5
set prog_output "ans = 1"
do_test s-5.m

set test index-s-6
set prog_output "ans = 1"
do_test s-6.m

set test index-s-7
set prog_output "ans = 1"
do_test s-7.m

set test index-s-8
set prog_output "error:.*"
do_test s-8.m

set test index-s-9
set prog_output "error:.*"
do_test s-9.m

set test index-s-10
set prog_output "error:.*"
do_test s-10.m

set test index-s-11
set prog_output "error:.*"
do_test s-11.m

set test index-s-12
set prog_output "error:.*"
do_test s-12.m

set test index-s-13
set prog_output "error:.*"
do_test s-13.m

set test index-s-14
set prog_output "error:.*"
do_test s-14.m

set test index-s-15
set prog_output "error:.*"
do_test s-15.m

set test index-s-16
set prog_output "error:.*"
do_test s-16.m

set test index-s-17
set prog_output "error:.*"
do_test s-17.m

set test index-s-18
set prog_output "error:.*"
do_test s-18.m

set test index-s-19
set prog_output "error:.*"
do_test s-19.m

set test index-s-20
set prog_output "error:.*"
do_test s-20.m

## vector tests

set test index-v-1
set prog_output "ans = 4"
do_test v-1.m

set test index-v-2
set prog_output "ans = 3"
do_test v-2.m

set test index-v-3
set prog_output "ans = 1"
do_test v-3.m

set test index-v-4
set prog_output "ans = 1"
do_test v-4.m

set test index-v-5
set prog_output "ans = 2"
do_test v-5.m

set test index-v-6
set prog_output "ans = 1"
do_test v-6.m

set test index-v-7
set prog_output "ans = 1"
do_test v-7.m

set test index-v-8
set prog_output "error:.*"
do_test v-8.m

set test index-v-9
set prog_output "error:.*"
do_test v-9.m

set test index-v-10
set prog_output "error:.*"
do_test v-10.m

set test index-v-11
set prog_output "ans = 1"
do_test v-11.m

set test index-v-12
set prog_output "error:.*"
do_test v-12.m

set test index-v-13
set prog_output "ans = 1"
do_test v-13.m

set test index-v-14
set prog_output "ans = 1"
do_test v-14.m

set test index-v-15
set prog_output "ans = 1"
do_test v-15.m

## matrix tests

set test index-m-1
set prog_output "ans = 1"
do_test m-1.m

set test index-m-2
set prog_output "ans = 1"
do_test m-2.m

set test index-m-3
set prog_output "error:.*"
do_test m-3.m

set test index-m-4
set prog_output "error:.*"
do_test m-4.m
