set test infnan-1
set prog_output "^ans = 0"
do_test infnan-1.m

set test infnan-2
set prog_output "^ans = 1"
do_test infnan-2.m

set test infnan-3
set prog_output "^ans = 0"
do_test infnan-3.m

set test infnan-4
set prog_output "^ans = 0"
do_test infnan-4.m

set test infnan-5
set prog_output "^ans = 0"
do_test infnan-5.m

set test infnan-6
set prog_output "^ans = 1"
do_test infnan-6.m

set test infnan-7
set prog_output "^ans = 1"
do_test infnan-7.m

set test infnan-8
set prog_output "^ans = 0"
do_test infnan-8.m

set test infnan-9
set prog_output "^ans = 0"
do_test infnan-9.m
