set test for-1
set prog_output "1"
do_test for-1.m

set test for-2
set prog_output "1234"
do_test for-2.m

set test for-3
set prog_output "1234"
do_test for-3.m

set test for-4
set prog_output "1324"
do_test for-4.m

set test for-5
set prog_output "1"
do_test for-5.m

set test for-6
set prog_output "1234"
do_test for-6.m

set test for-7
set prog_output "1324"
do_test for-7.m

set test for-8
set prog_output "12"
do_test for-8.m

set test for-9
set prog_output "34"
do_test for-9.m
