set test compan-1
set prog_output "^ans = 1"
do_test compan-1.m

set test compan-2
set prog_output "^ans = 1"
do_test compan-2.m

set test compan-3
set prog_output "^ans = 1"
do_test compan-3.m

set test compan-4
set prog_output "^ans = 1"
do_test compan-4.m

set test compan-5
set prog_output "^error:.*"
do_test compan-5.m

set test compan-6
set prog_output "^error:.*"
do_test compan-6.m

set test conv-1
set prog_output "^ans = 1"
do_test conv-1.m

set test conv-2
set prog_output "^ans = 1"
do_test conv-2.m

set test conv-3
set prog_output "^ans = 1"
do_test conv-3.m

set test conv-4
set prog_output "^error:.*"
do_test conv-4.m

set test conv-5
set prog_output "^ans = 6"
do_test conv-5.m

set test conv-6
set prog_output "^error:.*"
do_test conv-6.m

set test deconv-1
set prog_output "^ans = 1"
do_test deconv-1.m

set test deconv-2
set prog_output "^ans = 1"
do_test deconv-2.m

set test deconv-3
set prog_output "^ans = 1"
do_test deconv-3.m

set test deconv-4
set prog_output "^error:.*"
do_test deconv-4.m

set test deconv-5
set prog_output "^error:.*"
do_test deconv-5.m

set test poly-1
set prog_output "^ans = 1"
do_test poly-1.m

set test poly-2
set prog_output "^ans = 1"
do_test poly-2.m

set test poly-3
set prog_output "^usage:.*"
do_test poly-3.m

set test poly-4
set prog_output "^ans = 1"
do_test poly-4.m

set test polyderiv-1
set prog_output "^ans = 1"
do_test polyderiv-1.m

set test polyderiv-2
set prog_output "^ans = 1"
do_test polyderiv-2.m

set test polyderiv-3
set prog_output "^error:.*"
do_test polyderiv-3.m

set test polyderiv-4
set prog_output "^error:.*"
do_test polyderiv-4.m

set test polyfit-1
set prog_output "^ans = 1"
do_test polyfit-1.m

set test polyfit-2
set prog_output "^ans = 1"
do_test polyfit-2.m

set test polyfit-3
set prog_output "^error:.*"
do_test polyfit-3.m

set test polyfit-4
set prog_output "^usage:.*"
do_test polyfit-4.m

set test polyfit-5
set prog_output "^error:.*"
do_test polyfit-5.m

set test polyinteg-1
set prog_output "^ans = 1"
do_test polyinteg-1.m

set test polyinteg-2
set prog_output "^ans = 1"
do_test polyinteg-2.m

set test polyinteg-3
set prog_output "^ans = 1"
do_test polyinteg-3.m

set test polyinteg-4
set prog_output "^error:.*"
do_test polyinteg-4.m

set test polyreduce-1
set prog_output "^ans = 1"
do_test polyreduce-1.m

set test polyreduce-2
set prog_output "^ans = 1"
do_test polyreduce-2.m

set test polyreduce-3
set prog_output "^ans = 1"
do_test polyreduce-3.m

set test polyreduce-4
set prog_output "^ans = 1"
do_test polyreduce-4.m

set test polyreduce-5
set prog_output "^error:.*"
do_test polyreduce-5.m

set test polyval-1
set prog_output "^ans = 1"
do_test polyval-1.m

set test polyval-2
set prog_output "^ans = 1"
do_test polyval-2.m

set test polyval-3
set prog_output "^ans = 1"
do_test polyval-3.m

set test polyval-4
set prog_output "^ans = 1"
do_test polyval-4.m

set test polyval-5
set prog_output "^error:.*"
do_test polyval-5.m

set test polyval-6
set prog_output "^ans = 1"
do_test polyval-6.m

set test polyvalm-1
set prog_output "^ans = 1"
do_test polyvalm-1.m

set test polyvalm-2
set prog_output "^error:.*"
do_test polyvalm-2.m

set test residue-1
set prog_output "^ans = 1"
do_test residue-1.m

set test roots-1
set prog_output "^ans = 1"
do_test roots-1.m

set test roots-2
set prog_output "^ans = 1"
do_test roots-2.m

set test roots-3
set prog_output "^usage:.*"
do_test roots-3.m
