## The following functions need to have tests written for them:

# mahalanobis (test for success)
# skewness (test for success)

set test mean-1
set prog_output "ans = 1"
do_test mean-1.m

set test mean-2
set prog_output "usage:.*"
do_test mean-2.m

set test mean-3
set prog_output "usage:.*"
do_test mean-3.m

set test median-1
set prog_output "ans = 1"
do_test median-1.m

set test median-2
set prog_output "usage:.*"
do_test median-2.m

set test median-3
set prog_output "usage:.*"
do_test median-3.m

set test std-1
set prog_output "ans = 1"
do_test std-1.m

set test std-2
set prog_output "usage:.*"
do_test std-2.m

set test std-3
set prog_output "usage:.*"
do_test std-3.m

set test cov-1
set prog_output "ans = 1"
do_test cov-1.m

set test cov-2
set prog_output "usage:.*"
do_test cov-2.m

set test cov-3
set prog_output "usage:.*"
do_test cov-3.m

set test corrcoef-1
set prog_output "ans = 1"
do_test corrcoef-1.m

set test corrcoef-2
set prog_output "usage:.*"
do_test corrcoef-2.m

set test corrcoef-3
set prog_output "usage:.*"
do_test corrcoef-3.m

set test kurtosis-1
set prog_output "ans = 1"
do_test kurtosis-1.m

set test kurtosis-2
set prog_output "usage:.*"
do_test kurtosis-2.m

set test kurtosis-3
set prog_output "usage:.*"
do_test kurtosis-3.m

# set test mahalanobis-1
# set prog_output "ans = 1"
# do_test mahalanobis-1.m

set test mahalanobis-2
set prog_output "usage:.*"
do_test mahalanobis-2.m

set test mahalanobis-3
set prog_output "usage:.*"
do_test mahalanobis-3.m

# set test skewness-1
# set prog_output "ans = 1"
# do_test skewness-1.m

set test skewness-2
set prog_output "usage:.*"
do_test skewness-2.m

set test skewness-3
set prog_output "usage:.*"
do_test skewness-3.m
