## Tests with:
##
## prefer_zero_one_indexing == "false"
## prefer_column_vectors    == "true"
## do_fortran_indexing      == "false"

## scalar tests

set test zero-one-ftf-s-1
set prog_output "error:.*"
do_test s-1.m

set test zero-one-ftf-s-2
set prog_output "ans = *1"
do_test s-2.m

set test zero-one-ftf-s-3
set prog_output "ans = *1"
do_test s-3.m

set test zero-one-ftf-s-4
set prog_output "ans = *1"
do_test s-4.m

## vector tests

set test zero-one-ftf-v-1
set prog_output "ans = *1"
do_test v-1.m

set test zero-one-ftf-v-2
set prog_output "ans = *1"
do_test v-2.m

set test zero-one-ftf-v-3
set prog_output "ans = *1"
do_test v-3.m

set test zero-one-ftf-v-4
set prog_output "ans = *1"
do_test v-4.m

## matrix tests

set test zero-one-ftf-m-1
set prog_output "error:.*"
do_test m-1.m

set test zero-one-ftf-m-2
set prog_output "error:.*"
do_test m-2.m

set test zero-one-ftf-m-3
set prog_output "error:.*"
do_test m-3.m

set test zero-one-ftf-m-4
set prog_output "ans = *1"
do_test m-4.m

set test zero-one-ftf-m-5
set prog_output "ans = *1"
do_test m-5.m

set test zero-one-ftf-m-6
set prog_output "ans = *1"
do_test m-6.m

set test zero-one-ftf-m-7
set prog_output "ans = *1"
do_test m-7.m

set test zero-one-ftf-m-8
set prog_output "ans = *1"
do_test m-8.m

set test zero-one-ftf-m-9
set prog_output "ans = *1"
do_test m-9.m

set test zero-one-ftf-m-10
set prog_output "ans = *1"
do_test m-10.m

set test zero-one-ftf-m-11
set prog_output "ans = *1"
do_test m-11.m

set test zero-one-ftf-m-12
set prog_output "ans = *1"
do_test m-12.m

set test zero-one-ftf-m-13
set prog_output "ans = *1"
do_test m-13.m

set test zero-one-ftf-m-14
set prog_output "ans = *1"
do_test m-14.m

set test zero-one-ftf-m-15
set prog_output "ans = *1"
do_test m-15.m

set test zero-one-ftf-m-16
set prog_output "ans = *1"
do_test m-16.m

set test zero-one-ftf-m-17
set prog_output "ans = *1"
do_test m-17.m

set test zero-one-ftf-m-18
set prog_output "ans = *1"
do_test m-18.m

set test zero-one-ftf-m-19
set prog_output "ans = *1"
do_test m-19.m

set test zero-one-ftf-m-20
set prog_output "ans = *1"
do_test m-20.m

set test zero-one-ftf-m-21
set prog_output "ans = *1"
do_test m-21.m

set test zero-one-ftf-m-22
set prog_output "ans = *1"
do_test m-22.m

set test zero-one-ftf-m-23
set prog_output "ans = *1"
do_test m-23.m

set test zero-one-ftf-m-24
set prog_output "ans = *1"
do_test m-24.m

set test zero-one-ftf-m-25
set prog_output "ans = *1"
do_test m-25.m

set test zero-one-ftf-m-26
set prog_output "ans = *1"
do_test m-26.m

set test zero-one-ftf-m-27
set prog_output "ans = *1"
do_test m-27.m

set test zero-one-ftf-m-28
set prog_output "ans = *1"
do_test m-28.m

set test zero-one-ftf-m-29
set prog_output "ans = *1"
do_test m-29.m

set test zero-one-ftf-m-30
set prog_output "ans = *1"
do_test m-30.m

set test zero-one-ftf-m-31
set prog_output "ans = *1"
do_test m-31.m

set test zero-one-ftf-m-32
set prog_output "ans = *1"
do_test m-32.m

set test zero-one-ftf-m-33
set prog_output "ans = *1"
do_test m-33.m

set test zero-one-ftf-m-34
set prog_output "ans = *1"
do_test m-34.m

set test zero-one-ftf-m-35
set prog_output "ans = *1"
do_test m-35.m

set test zero-one-ftf-m-36
set prog_output "ans = *1"
do_test m-36.m
