@c Copyright (C) 1996, 1997 John W. Eaton
@c This is part of the Octave manual.
@c For copying conditions, see the file gpl.texi.

@cindex amusements
@node Amusements, Tips, Programming Utilities, Top
@chapter Amusements

@cindex lottery numbers
@cindex numbers, lottery
@deftypefn {Function File} {} texas_lotto ()
Octave cannot promise that you will actually win the lotto, but it can
pick your numbers for you.  The function @code{texas_lotto} will select
six numbers between 1 and 50.
@end deftypefn

@cindex prime numbers
@cindex numbers, prime
@deftypefn {Function File} {} list_primes (@var{n})
Computes the first @var{n} primes using a brute-force algorithm.
@end deftypefn

@findex casesen
@findex flops
@findex exit
@findex quit
@findex warranty
Other amusing functions include @code{casesen}, @code{flops},
@code{sombrero}, @code{exit}, @code{quit}, and @code{warranty}.
