@c ------------------------------------------------------------------------

@node Linear Programming
@chapter Linear Programming
@cindex LP
@cindex linear programming

@example
class LP
  LP (void)
  LP (const ColumnVector& c)
  LP (const ColumnVector& c, const Bounds& b)
  LP (const ColumnVector& c, const Bounds& b, const LinConst& lc)
  LP (const ColumnVector& c,                  const LinConst& lc)

  virtual ColumnVector minimize (void)
  virtual ColumnVector minimize (double& objf)
  virtual ColumnVector minimize (double& objf, int& inform)
  virtual ColumnVector minimize (double& objf, int& inform, ColumnVector& lambda) = 0

class LPsolve : public LP
  LPsolve (void) : LP ()

  LPsolve (const ColumnVector& c) : LP (c)

  LPsolve (const ColumnVector& c, const Bounds& b) : LP (c, b)

  LPsolve (const ColumnVector& c, const Bounds& b, const LinConst& lc)
    : LP (c, b, lc)

  LPsolve (const ColumnVector& c, const LinConst& lc) : LP (c, lc)

  virtual ColumnVector minimize (double& objf, int& inform, ColumnVector& lambda)
@end example

