.\" Copyright (C) 2000-2011 Dirk Eddelbuettel
.\"
.\" This file is part of Octave.
.\"
.\" Octave is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 3 of the License, or (at
.\" your option) any later version.
.\"
.\" Octave is distributed in the hope that it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with Octave; see the file COPYING.  If not, see
.\" <http://www.gnu.org/licenses/>.
.\"
.\" This page was contributed by Dirk Eddelbuettel <edd@debian.org>
.\"
.TH MKOCTFILE 1 "1 November 2002" "GNU Octave"
.SH NAME
mkoctfile \- Compile dynamic-load modules for GNU Octave
.SH SYNOPSIS
.BR mkoctfile\  [\-IDIR]\ [\-DDEF]\ [\-lLIB]\ [\-LDIR]\ [\-M|\-\-depend]
\ [\-c]\ [\-o FILE|\-\-output FILE]\ [\-p VAR|\-\-print VAR]\ [\-s|\-\-strip]
\ [\-v|\-\-verbose]\ [\-h|\-?|\-\-help]\ \fIfile\fP .\|.\|.
.SH DESCRIPTION
.PP
\fImkoctfile\fP is used to compile source C, C++ or Fortran source code in
dynamically loadable
.I .oct
file for
.BR octave (1).
.SH OPTIONS
\fImkoctfile\fP accepts the following options:
.TP 8
.B \-IDIR
Add include directory DIR to compile commands.
.TP 8
.B \-DDEF
Add definition DEF to compiler call.
.TP 8
.B \-lLIB
Add library LIB to link command.
.TP 8
.B \-LDIR
Add library directory DIR to link command.
.TP 8
.B \-M|\-\-depend
Generate dependency files (.d) for C and C++ source files.
.TP 8
.B \-c
Compile but do not link.
.TP 8
.B \-o FILE|\-\-output FILE
Output file name; default extension is .oct (or .mex if \-\-mex is
specified) unless linking a stand-alone executable.
.TP
.B \-p VAR|\-\-print VAR
Print configuration variable VAR.  Recognized variables are:
.RS
    ALL_CFLAGS                FFTW_LIBS
    ALL_CXXFLAGS              FLIBS
    ALL_FFLAGS                FPICFLAG
    ALL_LDFLAGS               INCFLAGS
    BLAS_LIBS                 LDFLAGS
    CC                        LD_CXX
    CFLAGS                    LD_STATIC_FLAG
    CPICFLAG                  LFLAGS
    CPPFLAGS                  LIBCRUFT
    CXX                       LIBOCTAVE
    CXXFLAGS                  LIBOCTINTERP
    CXXPICFLAG                LIBREADLINE
    DEPEND_EXTRA_SED_PATTERN  LIBS
    DEPEND_FLAGS              OCTAVE_LIBS
    DL_LD                     RDYNAMIC_FLAG
    DL_LDFLAGS                RLD_FLAG
    F2C                       SED
    F2CFLAGS                  XTRA_CFLAGS
    F77                       XTRA_CXXFLAGS
    FFLAGS
.RE
.TP 8
.B \-\-link-stand-alone
Link a stand-alone executable file.
.TP 8
.B \-\-mex
Assume we are creating a MEX file.  Set the default output extension
to .mex.
.TP 8
.B \-s|--strip
Strip the output file.
.TP 8
.B \-v|--verbose
Echo commands as they are executed.
.TP 8
.B file
Compile or link file. Recognised file types are
.RS
    .c    C source
    .cc   C++ source
    .C    C++ source
    .cpp  C++ source
    .f    Fortran source
    .F    Fortran source
    .o    object file
    .a    library file
.SH SEE ALSO
.BR octave (1).
.RE
.SH AUTHOR
John W. Eaton <jwe@octave.org>

This manual page was contributed by Dirk Eddelbuettel
<edd@debian.org> for the Debian GNU/Linux distribution but
may be used by others.
