.\" --------------------------------------------------------------------
.\"
.\" Copyright (C) 2003-2026 The Octave Project Developers
.\"
.\" See the file COPYRIGHT.md in the top-level directory of this
.\" or <https://octave.org/copyright/>.
.\"
.\" This file is part of Octave.
.\"
.\" Octave is free software: you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" Octave is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with Octave; see the file COPYING.  If not, see
.\" <https://www.gnu.org/licenses/>.
.\"
.\" --------------------------------------------------------------------
.\"
.de Vb \" (V)erbatim (b)egin.  Use fixed width font and no justification
.ft CW
.nf
..
.de Ve \" (V)erbatim (e)nd.  Return to regular font and justification
.ft R
.fi
..
.\" --------------------------------------------------------------------
.TH octave-config 1 "April 2026" "GNU Octave"
.SH NAME
octave\-config \- GNU Octave component and library information retrieval
.SH SYNOPSIS
\fBoctave-config\fP [\fIoption\fP]\|.\|.\|.\&
.SH DESCRIPTION
.B octave\-config
is a tool to obtain directory information for \fB.oct\fP and \fB.m\fP files for
.MR octave 1 .
.SH OPTIONS
.TP
.B \-\-m\-site\-dir
Display the main directory for local, or site-specific, \fB.m\fP script files.
.TP
.B \-\-oct\-site\-dir
Display the main directory for local, or site-specific, \fB.oct\fP dynamic-link libraries.
.TP
.B \-p \fIVAR\fP\fR,\fB \-\-print \fIVAR\fP
Print the default value of the Octave configuration variable \fIVAR\fP.
Recognized variables are:

.RS
.Vb
    API_VERSION                 LOCALARCHLIBDIR
    ARCHLIBDIR                  LOCALFCNFILEDIR
    BINDIR                      LOCALOCTFILEDIR
    CANONICAL_HOST_TYPE         LOCALSTARTUPFILEDIR
    DATADIR                     LOCALVERARCHLIBDIR
    DATAROOTDIR                 LOCALVERFCNFILEDIR
    DEFAULT_PAGER               LOCALVEROCTFILEDIR
    EXEEXT                      MAN1DIR
    FCNFILEDIR                  MAN1EXT
    IMAGEDIR                    MANDIR
    INCLUDEDIR                  OCTAVE_EXEC_HOME
    INFODIR                     OCTAVE_HOME
    INFOFILE                    OCTDATADIR
    LIBDIR                      OCTDOCDIR
    LIBEXECDIR                  OCTFILEDIR
    LOCALAPIARCHLIBDIR          OCTFONTSDIR
    LOCALAPIFCNFILEDIR          OCTINCLUDEDIR
    LOCALAPIOCTFILEDIR          OCTLIBDIR
    LOCALAPIPKGDIR              STARTUPFILEDIR
                                VERSION
.Ve
.RE
.TP
.B \-v\fR,\fB \-\-version
Display the version number of
.MR octave 1 .
.TP
\fB\-h\fP, \fB\-\-help\fP
Print help message.
.SH AUTHOR
John W. Eaton and many others.  The list of contributors to the Octave project
may be shown from within \%\fBoctave\fP by executing
"\fB\%doc \%Acknowledgements\fP".  The list is also available online at
.UR https://\:\%docs.octave.org/\:\%latest/\:\%Acknowledgements\:\%.html
.UE .
.SH "SEE ALSO"
.MR octave 1 .
