.\" Man page contributed by Dirk Eddelbuettel <edd@debian.org>
.\" and released under the GNU GPL
.TH OCTAVE-CONFIG 1 "19 February 2003" "GNU Octave"
.SH NAME
octave-config - GNU Octave component and library information retrieval
.SH SYNOPSIS
.B octave-config
.RI [ options ]
.SH DESCRIPTION
.PP
.B octave-config
is a tool to obtain directory information for 
.I .oct
and 
.I .m
files for
.BR octave (1).
.SH OPTIONS
.B octave-config
accepts the following options:
.TP 8
.B \--m-site-dir
Display the main directory for local, or site-specific, .m script files.
.TP 8
.B \--oct-site-dir
Display the main directory for local, or site-specific, .oct dynamic-link libraries.
.TP 8
.B \-p|\-\-print VAR
Print the default value of the Octave configuration variable VAR.
Recognized variables are:
.RS
    CANONICAL_HOST_TYPE    LOCALFCNFILEDIR    
    DEFAULT_PAGER          LOCALFCNFILEPATH
    ARCHLIBDIR             LOCALOCTFILEDIR
    BINDIR                 LOCALOCTFILEPATH
    DATADIR                LOCALSTARTUPFILEDIR
    EXEC_PREFIX            LOCALVERARCHLIBDIR
    FCNFILEDIR             LOCALVERFCNFILEDIR
    FCNFILEPATH            LOCALVEROCTFILEDIR
    IMAGEDIR               MAN1DIR
    IMAGEPATH              MAN1EXT
    INCLUDEDIR             MANDIR
    INFODIR                OCTFILEDIR
    INFOFILE               OCTINCLUDEDIR
    LIBDIR                 OCTLIBDIR
    LIBEXECDIR             PREFIX
    LIBEXECDIR             STARTUPFILEDIR
    LOCALARCHLIBDIR        VERSION
.RE
.TP 8
.B \-v|\-\-version
Display the version number of 
.BR octave (1).
.TP 8
.B \-h|-?|--help
Display a help page about
.B octave-config
.SH AUTHOR
John W. Eaton <jwe@bevo.che.wisc.edu>

This manual page was contributed by Dirk Eddelbuettel <edd@debian.org> 
for the Debian GNU/Linux distribution but may be used by others.
