GNULIB_LINK_DEPS = \
  $(COPYSIGNF_LIBM)\
  $(COPYSIGN_LIBM)\
  $(FLOOR_LIBM)\
  $(GETHOSTNAME_LIB)\
  $(LIBSOCKET)\
  $(LIB_NANOSLEEP)\
  $(LIB_SELECT)\
  $(LTLIBINTL)\
  $(ROUNDF_LIBM)\
  $(ROUND_LIBM)\
  $(TRUNCF_LIBM)\
  $(TRUNC_LIBM)

LIBCRUFT_LINK_DEPS = \
	$(GNULIB_LINK_DEPS) \
  $(LAPACK_LIBS) \
  $(BLAS_LIBS) \
  $(FLIBS) \
  $(LIBS)

LIBCRUFT_LINK_OPTS =

