set test str-esc-1
set prog_output "ok"
do_test str-esc-1.m

set test str-esc-2
set prog_output "ok"
do_test str-esc-2.m

set test str-esc-3
set prog_output "ok"
do_test str-esc-3.m

set test str-esc-4
set prog_output "ok"
do_test str-esc-4.m

set test str-esc-5
set prog_output "ok"
do_test str-esc-5.m

set test str-esc-6
set prog_output "ok"
do_test str-esc-6.m

set test str-esc-7
set prog_output "ok"
do_test str-esc-7.m

set test str-esc-8
set prog_output "ok"
do_test str-esc-8.m

set test str-esc-9
set prog_output "ok"
do_test str-esc-9.m

set test str-esc-10
set prog_output "ok"
do_test str-esc-10.m

set test str-esc-11
set prog_output ".*unrecognized escape sequence.*"
do_test str-esc-11.m

set test str-esc-12
set prog_output "ok"
do_test str-esc-12.m

set test string_fill_char-1
set prog_output "ans = 1"
do_test string_fill_char-1.m

set test string_fill_char-2
set prog_output "ans = 1"
do_test string_fill_char-2.m

set test isstr-1
set prog_output "ans = 0"
do_test isstr-1.m

set test isstr-2
set prog_output "ans = 0"
do_test isstr-2.m

set test isstr-3
set prog_output "ans = 0"
do_test isstr-3.m

set test isstr-4
set prog_output "ans = 0"
do_test isstr-4.m

set test isstr-5
set prog_output "ans = 1"
do_test isstr-5.m

set test isstr-6
set prog_output "ans = 1"
do_test isstr-6.m

set test isstr-7
set prog_output "ans = 1"
do_test isstr-7.m

set test isstr-8
set prog_output "ans = 1"
do_test isstr-8.m

set test isstr-9
set prog_output "ans = 0"
do_test isstr-9.m

set test isstr-10
set prog_output "\n... isstr:.*"
do_test isstr-10.m

set test isstr-11
set prog_output "\n... isstr:.*"
do_test isstr-11.m

# blanks
# int2str
# num2str
# setstr
# strcat
# str2mat
# deblank
# findstr
# index
# rindex
# split
# strcmp
# strrep
# substr
# bin2dec
# dec2bin
# dec2hex
# hex2dec
# str2num
# undo_string_escapes

# toascii
# tolower
# toupper

set test isalnum-1
set prog_output "ans = 1"
do_test isalnum-1.m

set test isalnum-2
set prog_output "error:.*"
do_test isalnum-2.m

set test isalnum-3
set prog_output "error:.*"
do_test isalnum-3.m

set test isalpha-1
set prog_output "ans = 1"
do_test isalpha-1.m

set test isalpha-2
set prog_output "error:.*"
do_test isalpha-2.m

set test isalpha-3
set prog_output "error:.*"
do_test isalpha-3.m

set test isascii-1
set prog_output "ans = 1"
do_test isascii-1.m

set test isascii-2
set prog_output "error:.*"
do_test isascii-2.m

set test isascii-3
set prog_output "error:.*"
do_test isascii-3.m

set test iscntrl-1
set prog_output "ans = 1"
do_test iscntrl-1.m

set test iscntrl-2
set prog_output "error:.*"
do_test iscntrl-2.m

set test iscntrl-3
set prog_output "error:.*"
do_test iscntrl-3.m

set test isdigit-1
set prog_output "ans = 1"
do_test isdigit-1.m

set test isdigit-2
set prog_output "error:.*"
do_test isdigit-2.m

set test isdigit-3
set prog_output "error:.*"
do_test isdigit-3.m

set test isgraph-1
set prog_output "ans = 1"
do_test isgraph-1.m

set test isgraph-2
set prog_output "error:.*"
do_test isgraph-2.m

set test isgraph-3
set prog_output "error:.*"
do_test isgraph-3.m

set test islower-1
set prog_output "ans = 1"
do_test islower-1.m

set test islower-2
set prog_output "error:.*"
do_test islower-2.m

set test islower-3
set prog_output "error:.*"
do_test islower-3.m

set test isprint-1
set prog_output "ans = 1"
do_test isprint-1.m

set test isprint-2
set prog_output "error:.*"
do_test isprint-2.m

set test isprint-3
set prog_output "error:.*"
do_test isprint-3.m

set test ispunct-1
set prog_output "ans = 1"
do_test ispunct-1.m

set test ispunct-2
set prog_output "error:.*"
do_test ispunct-2.m

set test ispunct-3
set prog_output "error:.*"
do_test ispunct-3.m

set test isspace-1
set prog_output "ans = 1"
do_test isspace-1.m

set test isspace-2
set prog_output "error:.*"
do_test isspace-2.m

set test isspace-3
set prog_output "error:.*"
do_test isspace-3.m

set test isupper-1
set prog_output "ans = 1"
do_test isupper-1.m

set test isupper-2
set prog_output "error:.*"
do_test isupper-2.m

set test isupper-3
set prog_output "error:.*"
do_test isupper-3.m

set test isxdigit-1
set prog_output ""ans = 1
do_test isxdigit-1.m

set test isxdigit-2
set prog_output ""error:.*
do_test isxdigit-2.m

set test isxdigit-3
set prog_output ""error:.*
do_test isxdigit-3.m
