#! /bin/sh
#
# Copyright (C) 2002, 2003, 2007 John W. Eaton
#
# This file is part of Octave.
# 
# Octave is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.
# 
# Octave is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Octave; see the file COPYING.  If not, see
# <http://www.gnu.org/licenses/>.

if [ $# -eq 1 ]; then
  dir="$1"
else
  echo "usage: mkpkgadd directory" 1>&2
  exit 1
fi

cd $dir

m_files=`ls *.m`
cxx_files=`ls *.cc`

if [ -n "$m_files" ]; then
  sed -n 's/^[#%][#%]* *PKG_ADD: *//p' $m_files
fi

if [ -n "$cxx_files" ]; then
  sed -n -e 's,^//* *PKG_ADD: *,,p' \
         -e 's,^/\** *PKG_ADD: *\(.*\) \*/$,\1,p' $cxx_files
fi
