#! /bin/sh

if [ $# -eq 1 ]; then
  dir="$1"
else
  echo "usage: mkpkgadd directory" 1>&2
  exit 1
fi

cd $dir

m_files=`ls *.m`
cxx_files=`ls *.cc`

if [ -n "$m_files" ]; then
  sed -n 's/^[#%][#%]* *PKG_ADD: *//p' $m_files
fi

if [ -n "$cxx_files" ]; then
  sed -n -e 's,^//* *PKG_ADD: *,,p' \
         -e 's,^/\** *PKG_ADD: *\(.*\) \*/$,\1,p' $cxx_files
fi
