#! /bin/sh
# info-emacs-octave-help
#
# Copyright (C) 1996, 1997, 2005, 2007 Kurt Hornik
#
# This file is part of Octave.
# 
# Octave is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.
# 
# Octave is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Octave; see the file COPYING.  If not, see
# <http://www.gnu.org/licenses/>.

# Written by KH <Kurt.Hornik@wu-wien.ac.at> on 1996/07/01
# Updated by KH on 1997/03/04

# Make Octave's `help -i' use Emacs octave-help.
# Requires a running Emacs and gnuserv.

cmd="(require 'octave-hlp)"
if [ $3 = "--directory" ];
then
    cmd="$cmd (add-to-list 'Info-directory-list \"$4\")"
    shift 2
fi
cmd="$cmd (octave-help \"$4\")"
gnuclient -batch -q -eval "$cmd"
