#! /bin/sh
# info-emacs-info
#
# Copyright (C) 1996, 2005, 2007 Kurt Hornik
#
# This file is part of Octave.
# 
# Octave is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.
# 
# Octave is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Octave; see the file COPYING.  If not, see
# <http://www.gnu.org/licenses/>.

# Written by Kurt Hornik <Kurt.Hornik@wu-wien.ac.at> on 1996/07/01

# Make Octave's `help -i' use Emacs info.
# Requires a running Emacs and gnuserv.
cmd="(Info-find-node \"$2\" \"Top\")"
if [ $3 = "--directory" ];
then
	cmd="(add-to-list 'Info-directory-list \"$4\") $cmd"
	shift 2
fi
cmd="(require 'info) $cmd"
[ $4 ] && cmd="$cmd (Info-index \"$4\")"
gnuclient -batch -q -eval "$cmd"
