.\" Copyright (C) 2003, 2006, 2007 Dirk Eddelbuettel
.\"
.\" This file is part of Octave.
.\"
.\" Octave is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 3 of the License, or (at
.\" your option) any later version.
.\"
.\" Octave is distributed in the hope that it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
.\" for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with Octave; see the file COPYING.  If not, see
.\" <http://www.gnu.org/licenses/>.
.\"
.\" This page was contributed by Dirk Eddelbuettel <edd@debian.org>
.\" 
.TH OCTAVE-TAGS 1 "31 October 2001" "GNU Octave"
.SH NAME
OCTAVE-TAGS - Generate Emacs tags file from GNU Octave code
.SH SYNOPSIS
.BR octave-tags\  [--include\ dir]
\fIfile\fP .\|.\|.  
.SH DESCRIPTION
.PP
.B octave-tags
program is used to create a tag table file, in a format understood by 
.BR emacs (1)
and
.BR xemacs (1).
.B octave-tags
reads the files specified on the command line, and write a tag table  
(defaults: `TAGS') in the current working directory. Files specified with
relative file names will be  recorded in the tag table with file names
relative to the directory where the tag table resides.  Files specified  with
absolute file names will be recorded with absolute file names.

The 
.I --include
option can be used to specify another directoy with Octave files for which
tags shall be generated.
 
Tags are generated for function names and for global variables. For
global variables it doesn't work for more than one line global
variables.  
 
Tags are also created for lines of the form '###key foobar' so that
you can jump to this specific place just by typing `M-. foobar'.
Note that tags are not generated for scripts so that you have to add
a line by yourself of the form `###key <script-name>' if you want to
jump to it.  

.SH SEE ALSO
.BR etags (1).

.SH AUTHORS
Mario Storti <mstorti@minerva.unl.edu.ar>

This manual page was contributed by Dirk Eddelbuettel
<edd@debian.org> for the Debian GNU/Linux distribution but 
may be used by others.
