.\" Man page contributed by Dirk Eddelbuettel <edd@debian.org>
.\" and released under the GNU GPL
.TH OTAGS 1 "31 October 2001" "GNU Octave"
.SH NAME
OTAGS - Generate Emacs tags file from GNU Octave code
.SH SYNOPSIS
.BR otags\  [--include\ dir]
\fIfile\fP .\|.\|.  
.SH DESCRIPTION
.PP
.B otags
program is used to create a tag table file, in a format understood by 
.BR emacs (1)
and
.BR xemacs (1).
.B otags
reads the files specified on the command line, and write a tag table  
(defaults: `TAGS') in the current working directory. Files specified with
relative file names will be  recorded in the tag table with file names
relative to the directory where the tag table resides.  Files specified  with
absolute file names will be recorded with absolute file names.

The 
.I --include
option can be used to specify another directoy with Octave files for which
tags shall be generated.
 
Tags are generated for function names and for global variables. For
global variables it doesn't work for more than one line global
variables.  
 
Tags are also created for lines of the form '###key foobar' so that
you can jump to this specific place just by typing `M-. foobar'.
Note that tags are not generated for scripts so that you have to add
a line by yourself of the form `###key <script-name>' if you want to
jump to it.  

.SH SEE ALSO
.BR etags (1).

.SH AUTHORS
Mario Storti <mstorti@minerva.unl.edu.ar>

This manual page was contributed by Dirk Eddelbuettel
<edd@debian.org> for the Debian GNU/Linux distribution but 
may be used by others.
