@node Differential Algebraic Equations, Error Handling, Ordinary Differential Equations, Top
@chapter Differential Algebraic Equations
@cindex DAE

@deftypefn  {} {} DAE (void)
@deftypefnx  {} {} DAE (int @var{n})
@deftypefnx  {} {} DAE (const ColumnVector &@var{x}, double @var{time}, DAEFunc &@var{f})
@deftypefnx  {} {} DAE (const ColumnVector &@var{x}, ColumnVector &@var{xdot}, double @var{time}, DAEFunc &@var{f})
@end deftypefn

@deftypefn {} ColumnVector deriv (void)
@end deftypefn

@deftypefn {} {virtual void} initialize (const ColumnVector &@var{x}, double @var{t})
@deftypefnx {} {virtual void} initialize (const ColumnVector &@var{x}, ColumnVector &@var{xdot}, double @var{t})
@end deftypefn

@deftypefn {} ColumnVector integrate (double @var{t})
@end deftypefn

@deftypefn {} Matrix integrate (const ColumnVector &@var{tout}, Matrix &@var{xdot_out})
@deftypefnx {} Matrix integrate (const ColumnVector &@var{tout}, Matrix &@var{xdot_out}, const ColumnVector &@var{tcrit})
@end deftypefn
