#! /bin/sh
#
# Copyright (C) 1996, 1999, 2000, 2003, 2006, 2007 John W. Eaton
#
# This file is part of Octave.
# 
# Octave is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.
# 
# Octave is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Octave; see the file COPYING.  If not, see
# <http://www.gnu.org/licenses/>.

SED=${SED:-'sed'}

$SED -n -e '/^ *BEGIN_INSTALL_BUILTIN/{
  : loop
  s/BEGIN_INSTALL_BUILTIN//
  s/^#[ \t][ \t]*[0-9][0-9]*.*$//
  /END_INSTALL_BUILTIN/b done
  p
  n
  b loop
  : done
  s/END_INSTALL_BUILTIN//
  p
}'
