#! /bin/sh

SED=${SED:-'sed'}

$SED -n -e '/^ *BEGIN_INSTALL_BUILTIN/{
  : loop
  s/BEGIN_INSTALL_BUILTIN//
  s/^#[ \t][ \t]*[0-9][0-9]*.*$//
  /END_INSTALL_BUILTIN/b done
  p
  n
  b loop
  : done
  s/END_INSTALL_BUILTIN//
  p
}'
