EXTRA_DIST += lapack/module.mk

lapack/dlamc1.lo: FFLAGS += $(F77_FLOAT_STORE_FLAG)
lapack/slamc1.lo: FFLAGS += $(F77_FLOAT_STORE_FLAG)

LAPACK_SRC = \
  lapack/cbdsqr.f \
  lapack/cgbcon.f \
  lapack/cgbtf2.f \
  lapack/cgbtrf.f \
  lapack/cgbtrs.f \
  lapack/cgbtrs.f \
  lapack/cgebak.f \
  lapack/cgebal.f \
  lapack/cgebd2.f \
  lapack/cgebrd.f \
  lapack/cgecon.f \
  lapack/cgecon.f \
  lapack/cgeesx.f \
  lapack/cgeev.f \
  lapack/cgehd2.f \
  lapack/cgehrd.f \
  lapack/cgelq2.f \
  lapack/cgelq2.f \
  lapack/cgelqf.f \
  lapack/cgelsd.f \
  lapack/cgelss.f \
  lapack/cgelsy.f \
  lapack/cgeqp3.f \
  lapack/cgeqp3.f \
  lapack/cgeqpf.f \
  lapack/cgeqr2.f \
  lapack/cgeqrf.f \
  lapack/cgesvd.f \
  lapack/cgesv.f \
  lapack/cgesv.f \
  lapack/cgetf2.f \
  lapack/cgetrf.f \
  lapack/cgetri.f \
  lapack/cgetrs.f \
  lapack/cggbak.f \
  lapack/cggbak.f \
  lapack/cggbal.f \
  lapack/cggev.f \
  lapack/cgghrd.f \
  lapack/cgtsv.f \
  lapack/cgttrf.f \
  lapack/cgttrf.f \
  lapack/cgttrs.f \
  lapack/cgtts2.f \
  lapack/cheev.f \
  lapack/chetd2.f \
  lapack/chetrd.f \
  lapack/chetrd.f \
  lapack/chgeqz.f \
  lapack/chseqr.f \
  lapack/clabrd.f \
  lapack/clacgv.f \
  lapack/clacn2.f \
  lapack/clacn2.f \
  lapack/clacon.f \
  lapack/clacpy.f \
  lapack/cladiv.f \
  lapack/clahqr.f \
  lapack/clahr2.f \
  lapack/clahr2.f \
  lapack/clahrd.f \
  lapack/claic1.f \
  lapack/clals0.f \
  lapack/clalsa.f \
  lapack/clalsd.f \
  lapack/clalsd.f \
  lapack/clange.f \
  lapack/clanhe.f \
  lapack/clanhs.f \
  lapack/clantr.f \
  lapack/claqp2.f \
  lapack/claqp2.f \
  lapack/claqps.f \
  lapack/claqr0.f \
  lapack/claqr1.f \
  lapack/claqr2.f \
  lapack/claqr3.f \
  lapack/claqr3.f \
  lapack/claqr4.f \
  lapack/claqr5.f \
  lapack/clarfb.f \
  lapack/clarf.f \
  lapack/clarfg.f \
  lapack/clarfg.f \
  lapack/clarft.f \
  lapack/clarfx.f \
  lapack/clartg.f \
  lapack/clarzb.f \
  lapack/clarz.f \
  lapack/clarz.f \
  lapack/clarzt.f \
  lapack/clascl.f \
  lapack/claset.f \
  lapack/clasr.f \
  lapack/classq.f \
  lapack/classq.f \
  lapack/claswp.f \
  lapack/clatbs.f \
  lapack/clatrd.f \
  lapack/clatrs.f \
  lapack/clatrz.f \
  lapack/clatrz.f \
  lapack/clauu2.f \
  lapack/clauum.f \
  lapack/cpbcon.f \
  lapack/cpbtf2.f \
  lapack/cpbtrf.f \
  lapack/cpbtrf.f \
  lapack/cpbtrs.f \
  lapack/cpocon.f \
  lapack/cpotf2.f \
  lapack/cpotrf.f \
  lapack/cpotri.f \
  lapack/cpotri.f \
  lapack/cpotrs.f \
  lapack/cptsv.f \
  lapack/cpttrf.f \
  lapack/cpttrs.f \
  lapack/cptts2.f \
  lapack/cptts2.f \
  lapack/crot.f \
  lapack/csrscl.f \
  lapack/csteqr.f \
  lapack/ctgevc.f \
  lapack/ctrcon.f \
  lapack/ctrcon.f \
  lapack/ctrevc.f \
  lapack/ctrexc.f \
  lapack/ctrsen.f \
  lapack/ctrsyl.f \
  lapack/ctrti2.f \
  lapack/ctrti2.f \
  lapack/ctrtri.f \
  lapack/ctrtrs.f \
  lapack/ctzrzf.f \
  lapack/cung2l.f \
  lapack/cung2r.f \
  lapack/cung2r.f \
  lapack/cungbr.f \
  lapack/cunghr.f \
  lapack/cungl2.f \
  lapack/cunglq.f \
  lapack/cungql.f \
  lapack/cungql.f \
  lapack/cungqr.f \
  lapack/cungtr.f \
  lapack/cunm2r.f \
  lapack/cunmbr.f \
  lapack/cunml2.f \
  lapack/cunml2.f \
  lapack/cunmlq.f \
  lapack/cunmqr.f \
  lapack/cunmr3.f \
  lapack/cunmrz.f \
  lapack/dbdsqr.f \
  lapack/dbdsqr.f \
  lapack/dgbcon.f \
  lapack/dgbtf2.f \
  lapack/dgbtrf.f \
  lapack/dgbtrs.f \
  lapack/dgebak.f \
  lapack/dgebak.f \
  lapack/dgebal.f \
  lapack/dgebd2.f \
  lapack/dgebrd.f \
  lapack/dgecon.f \
  lapack/dgeesx.f \
  lapack/dgeesx.f \
  lapack/dgeev.f \
  lapack/dgehd2.f \
  lapack/dgehrd.f \
  lapack/dgelq2.f \
  lapack/dgelqf.f \
  lapack/dgelqf.f \
  lapack/dgelsd.f \
  lapack/dgelss.f \
  lapack/dgelsy.f \
  lapack/dgeqp3.f \
  lapack/dgeqpf.f \
  lapack/dgeqpf.f \
  lapack/dgeqr2.f \
  lapack/dgeqrf.f \
  lapack/dgesvd.f \
  lapack/dgesv.f \
  lapack/dgetf2.f \
  lapack/dgetf2.f \
  lapack/dgetrf.f \
  lapack/dgetri.f \
  lapack/dgetrs.f \
  lapack/dggbak.f \
  lapack/dggbal.f \
  lapack/dggbal.f \
  lapack/dggev.f \
  lapack/dgghrd.f \
  lapack/dgtsv.f \
  lapack/dgttrf.f \
  lapack/dgttrs.f \
  lapack/dgttrs.f \
  lapack/dgtts2.f \
  lapack/dhgeqz.f \
  lapack/dhseqr.f \
  lapack/dlabad.f \
  lapack/dlabrd.f \
  lapack/dlabrd.f \
  lapack/dlacn2.f \
  lapack/dlacon.f \
  lapack/dlacpy.f \
  lapack/dladiv.f \
  lapack/dlae2.f \
  lapack/dlae2.f \
  lapack/dlaed6.f \
  lapack/dlaev2.f \
  lapack/dlaexc.f \
  lapack/dlag2.f \
  lapack/dlahqr.f \
  lapack/dlahqr.f \
  lapack/dlahr2.f \
  lapack/dlahrd.f \
  lapack/dlaic1.f \
  lapack/dlaln2.f \
  lapack/dlals0.f \
  lapack/dlals0.f \
  lapack/dlalsa.f \
  lapack/dlalsd.f \
  lapack/dlamc1.f \
  lapack/dlamc2.f \
  lapack/dlamc3.f \
  lapack/dlamc3.f \
  lapack/dlamc4.f \
  lapack/dlamc5.f \
  lapack/dlamch.f \
  lapack/dlamrg.f \
  lapack/dlange.f \
  lapack/dlange.f \
  lapack/dlanhs.f \
  lapack/dlanst.f \
  lapack/dlansy.f \
  lapack/dlantr.f \
  lapack/dlanv2.f \
  lapack/dlanv2.f \
  lapack/dlapy2.f \
  lapack/dlapy3.f \
  lapack/dlaqp2.f \
  lapack/dlaqps.f \
  lapack/dlaqr0.f \
  lapack/dlaqr0.f \
  lapack/dlaqr1.f \
  lapack/dlaqr2.f \
  lapack/dlaqr3.f \
  lapack/dlaqr4.f \
  lapack/dlaqr5.f \
  lapack/dlaqr5.f \
  lapack/dlarfb.f \
  lapack/dlarf.f \
  lapack/dlarfg.f \
  lapack/dlarft.f \
  lapack/dlarfx.f \
  lapack/dlarfx.f \
  lapack/dlartg.f \
  lapack/dlarzb.f \
  lapack/dlarz.f \
  lapack/dlarzt.f \
  lapack/dlas2.f \
  lapack/dlas2.f \
  lapack/dlascl.f \
  lapack/dlasd0.f \
  lapack/dlasd1.f \
  lapack/dlasd2.f \
  lapack/dlasd3.f \
  lapack/dlasd3.f \
  lapack/dlasd4.f \
  lapack/dlasd5.f \
  lapack/dlasd6.f \
  lapack/dlasd7.f \
  lapack/dlasd8.f \
  lapack/dlasd8.f \
  lapack/dlasda.f \
  lapack/dlasdq.f \
  lapack/dlasdt.f \
  lapack/dlaset.f \
  lapack/dlasq1.f \
  lapack/dlasq1.f \
  lapack/dlasq2.f \
  lapack/dlasq3.f \
  lapack/dlasq4.f \
  lapack/dlasq5.f \
  lapack/dlasq6.f \
  lapack/dlasq6.f \
  lapack/dlasr.f \
  lapack/dlasrt.f \
  lapack/dlassq.f \
  lapack/dlasv2.f \
  lapack/dlaswp.f \
  lapack/dlaswp.f \
  lapack/dlasy2.f \
  lapack/dlatbs.f \
  lapack/dlatrd.f \
  lapack/dlatrs.f \
  lapack/dlatrz.f \
  lapack/dlatrz.f \
  lapack/dlauu2.f \
  lapack/dlauum.f \
  lapack/dlazq3.f \
  lapack/dlazq4.f \
  lapack/dorg2l.f \
  lapack/dorg2l.f \
  lapack/dorg2r.f \
  lapack/dorgbr.f \
  lapack/dorghr.f \
  lapack/dorgl2.f \
  lapack/dorglq.f \
  lapack/dorglq.f \
  lapack/dorgql.f \
  lapack/dorgqr.f \
  lapack/dorgtr.f \
  lapack/dorm2r.f \
  lapack/dormbr.f \
  lapack/dormbr.f \
  lapack/dorml2.f \
  lapack/dormlq.f \
  lapack/dormqr.f \
  lapack/dormr3.f \
  lapack/dormrz.f \
  lapack/dormrz.f \
  lapack/dpbcon.f \
  lapack/dpbtf2.f \
  lapack/dpbtrf.f \
  lapack/dpbtrs.f \
  lapack/dpocon.f \
  lapack/dpocon.f \
  lapack/dpotf2.f \
  lapack/dpotrf.f \
  lapack/dpotri.f \
  lapack/dpotrs.f \
  lapack/dptsv.f \
  lapack/dptsv.f \
  lapack/dpttrf.f \
  lapack/dpttrs.f \
  lapack/dptts2.f \
  lapack/drscl.f \
  lapack/dsteqr.f \
  lapack/dsteqr.f \
  lapack/dsterf.f \
  lapack/dsyev.f \
  lapack/dsytd2.f \
  lapack/dsytrd.f \
  lapack/dtgevc.f \
  lapack/dtgevc.f \
  lapack/dtrcon.f \
  lapack/dtrevc.f \
  lapack/dtrexc.f \
  lapack/dtrsen.f \
  lapack/dtrsyl.f \
  lapack/dtrsyl.f \
  lapack/dtrti2.f \
  lapack/dtrtri.f \
  lapack/dtrtrs.f \
  lapack/dtzrzf.f \
  lapack/dzsum1.f \
  lapack/dzsum1.f \
  lapack/icmax1.f \
  lapack/ieeeck.f \
  lapack/ilaenv.f \
  lapack/iparmq.f \
  lapack/izmax1.f \
  lapack/izmax1.f \
  lapack/sbdsqr.f \
  lapack/scsum1.f \
  lapack/sgbcon.f \
  lapack/sgbtf2.f \
  lapack/sgbtrf.f \
  lapack/sgbtrf.f \
  lapack/sgbtrs.f \
  lapack/sgebak.f \
  lapack/sgebal.f \
  lapack/sgebd2.f \
  lapack/sgebrd.f \
  lapack/sgebrd.f \
  lapack/sgecon.f \
  lapack/sgeesx.f \
  lapack/sgeev.f \
  lapack/sgehd2.f \
  lapack/sgehrd.f \
  lapack/sgehrd.f \
  lapack/sgelq2.f \
  lapack/sgelqf.f \
  lapack/sgelsd.f \
  lapack/sgelss.f \
  lapack/sgelsy.f \
  lapack/sgelsy.f \
  lapack/sgeqp3.f \
  lapack/sgeqpf.f \
  lapack/sgeqr2.f \
  lapack/sgeqrf.f \
  lapack/sgesvd.f \
  lapack/sgesvd.f \
  lapack/sgesv.f \
  lapack/sgetf2.f \
  lapack/sgetrf.f \
  lapack/sgetri.f \
  lapack/sgetrs.f \
  lapack/sgetrs.f \
  lapack/sggbak.f \
  lapack/sggbal.f \
  lapack/sggev.f \
  lapack/sgghrd.f \
  lapack/sgtsv.f \
  lapack/sgtsv.f \
  lapack/sgttrf.f \
  lapack/sgttrs.f \
  lapack/sgtts2.f \
  lapack/shgeqz.f \
  lapack/shseqr.f \
  lapack/shseqr.f \
  lapack/slabad.f \
  lapack/slabrd.f \
  lapack/slacn2.f \
  lapack/slacon.f \
  lapack/slacpy.f \
  lapack/slacpy.f \
  lapack/sladiv.f \
  lapack/slae2.f \
  lapack/slaed6.f \
  lapack/slaev2.f \
  lapack/slaexc.f \
  lapack/slaexc.f \
  lapack/slag2.f \
  lapack/slahqr.f \
  lapack/slahr2.f \
  lapack/slahrd.f \
  lapack/slaic1.f \
  lapack/slaic1.f \
  lapack/slaln2.f \
  lapack/slals0.f \
  lapack/slalsa.f \
  lapack/slalsd.f \
  lapack/slamc1.f \
  lapack/slamc1.f \
  lapack/slamc2.f \
  lapack/slamc3.f \
  lapack/slamc4.f \
  lapack/slamc5.f \
  lapack/slamch.f \
  lapack/slamch.f \
  lapack/slamrg.f \
  lapack/slange.f \
  lapack/slanhs.f \
  lapack/slanst.f \
  lapack/slansy.f \
  lapack/slansy.f \
  lapack/slantr.f \
  lapack/slanv2.f \
  lapack/slapy2.f \
  lapack/slapy3.f \
  lapack/slaqp2.f \
  lapack/slaqp2.f \
  lapack/slaqps.f \
  lapack/slaqr0.f \
  lapack/slaqr1.f \
  lapack/slaqr2.f \
  lapack/slaqr3.f \
  lapack/slaqr3.f \
  lapack/slaqr4.f \
  lapack/slaqr5.f \
  lapack/slarfb.f \
  lapack/slarf.f \
  lapack/slarfg.f \
  lapack/slarfg.f \
  lapack/slarft.f \
  lapack/slarfx.f \
  lapack/slartg.f \
  lapack/slarzb.f \
  lapack/slarz.f \
  lapack/slarz.f \
  lapack/slarzt.f \
  lapack/slas2.f \
  lapack/slascl.f \
  lapack/slasd0.f \
  lapack/slasd1.f \
  lapack/slasd1.f \
  lapack/slasd2.f \
  lapack/slasd3.f \
  lapack/slasd4.f \
  lapack/slasd5.f \
  lapack/slasd6.f \
  lapack/slasd6.f \
  lapack/slasd7.f \
  lapack/slasd8.f \
  lapack/slasda.f \
  lapack/slasdq.f \
  lapack/slasdt.f \
  lapack/slasdt.f \
  lapack/slaset.f \
  lapack/slasq1.f \
  lapack/slasq2.f \
  lapack/slasq3.f \
  lapack/slasq4.f \
  lapack/slasq4.f \
  lapack/slasq5.f \
  lapack/slasq6.f \
  lapack/slasr.f \
  lapack/slasrt.f \
  lapack/slassq.f \
  lapack/slassq.f \
  lapack/slasv2.f \
  lapack/slaswp.f \
  lapack/slasy2.f \
  lapack/slatbs.f \
  lapack/slatrd.f \
  lapack/slatrd.f \
  lapack/slatrs.f \
  lapack/slatrz.f \
  lapack/slauu2.f \
  lapack/slauum.f \
  lapack/slazq3.f \
  lapack/slazq3.f \
  lapack/slazq4.f \
  lapack/sorg2l.f \
  lapack/sorg2r.f \
  lapack/sorgbr.f \
  lapack/sorghr.f \
  lapack/sorghr.f \
  lapack/sorgl2.f \
  lapack/sorglq.f \
  lapack/sorgql.f \
  lapack/sorgqr.f \
  lapack/sorgtr.f \
  lapack/sorgtr.f \
  lapack/sorm2r.f \
  lapack/sormbr.f \
  lapack/sorml2.f \
  lapack/sormlq.f \
  lapack/sormqr.f \
  lapack/sormqr.f \
  lapack/sormr3.f \
  lapack/sormrz.f \
  lapack/spbcon.f \
  lapack/spbtf2.f \
  lapack/spbtrf.f \
  lapack/spbtrf.f \
  lapack/spbtrs.f \
  lapack/spocon.f \
  lapack/spotf2.f \
  lapack/spotrf.f \
  lapack/spotri.f \
  lapack/spotri.f \
  lapack/spotrs.f \
  lapack/sptsv.f \
  lapack/spttrf.f \
  lapack/spttrs.f \
  lapack/sptts2.f \
  lapack/sptts2.f \
  lapack/srscl.f \
  lapack/ssteqr.f \
  lapack/ssterf.f \
  lapack/ssyev.f \
  lapack/ssytd2.f \
  lapack/ssytd2.f \
  lapack/ssytrd.f \
  lapack/stgevc.f \
  lapack/strcon.f \
  lapack/strevc.f \
  lapack/strexc.f \
  lapack/strexc.f \
  lapack/strsen.f \
  lapack/strsyl.f \
  lapack/strti2.f \
  lapack/strtri.f \
  lapack/strtrs.f \
  lapack/strtrs.f \
  lapack/stzrzf.f \
  lapack/zbdsqr.f \
  lapack/zdrscl.f \
  lapack/zgbcon.f \
  lapack/zgbtf2.f \
  lapack/zgbtf2.f \
  lapack/zgbtrf.f \
  lapack/zgbtrs.f \
  lapack/zgebak.f \
  lapack/zgebal.f \
  lapack/zgebd2.f \
  lapack/zgebd2.f \
  lapack/zgebrd.f \
  lapack/zgecon.f \
  lapack/zgeesx.f \
  lapack/zgeev.f \
  lapack/zgehd2.f \
  lapack/zgehd2.f \
  lapack/zgehrd.f \
  lapack/zgelq2.f \
  lapack/zgelqf.f \
  lapack/zgelsd.f \
  lapack/zgelss.f \
  lapack/zgelss.f \
  lapack/zgelsy.f \
  lapack/zgeqp3.f \
  lapack/zgeqpf.f \
  lapack/zgeqr2.f \
  lapack/zgeqrf.f \
  lapack/zgeqrf.f \
  lapack/zgesvd.f \
  lapack/zgesv.f \
  lapack/zgetf2.f \
  lapack/zgetrf.f \
  lapack/zgetri.f \
  lapack/zgetri.f \
  lapack/zgetrs.f \
  lapack/zggbak.f \
  lapack/zggbal.f \
  lapack/zggev.f \
  lapack/zgghrd.f \
  lapack/zgghrd.f \
  lapack/zgtsv.f \
  lapack/zgttrf.f \
  lapack/zgttrs.f \
  lapack/zgtts2.f \
  lapack/zheev.f \
  lapack/zheev.f \
  lapack/zhetd2.f \
  lapack/zhetrd.f \
  lapack/zhgeqz.f \
  lapack/zhseqr.f \
  lapack/zlabrd.f \
  lapack/zlabrd.f \
  lapack/zlacgv.f \
  lapack/zlacn2.f \
  lapack/zlacon.f \
  lapack/zlacpy.f \
  lapack/zladiv.f \
  lapack/zladiv.f \
  lapack/zlahqr.f \
  lapack/zlahr2.f \
  lapack/zlahrd.f \
  lapack/zlaic1.f \
  lapack/zlals0.f \
  lapack/zlals0.f \
  lapack/zlalsa.f \
  lapack/zlalsd.f \
  lapack/zlange.f \
  lapack/zlanhe.f \
  lapack/zlanhs.f \
  lapack/zlanhs.f \
  lapack/zlantr.f \
  lapack/zlaqp2.f \
  lapack/zlaqps.f \
  lapack/zlaqr0.f \
  lapack/zlaqr1.f \
  lapack/zlaqr1.f \
  lapack/zlaqr2.f \
  lapack/zlaqr3.f \
  lapack/zlaqr4.f \
  lapack/zlaqr5.f \
  lapack/zlarfb.f \
  lapack/zlarfb.f \
  lapack/zlarf.f \
  lapack/zlarfg.f \
  lapack/zlarft.f \
  lapack/zlarfx.f \
  lapack/zlartg.f \
  lapack/zlartg.f \
  lapack/zlarzb.f \
  lapack/zlarz.f \
  lapack/zlarzt.f \
  lapack/zlascl.f \
  lapack/zlaset.f \
  lapack/zlaset.f \
  lapack/zlasr.f \
  lapack/zlassq.f \
  lapack/zlaswp.f \
  lapack/zlatbs.f \
  lapack/zlatrd.f \
  lapack/zlatrd.f \
  lapack/zlatrs.f \
  lapack/zlatrz.f \
  lapack/zlauu2.f \
  lapack/zlauum.f \
  lapack/zpbcon.f \
  lapack/zpbcon.f \
  lapack/zpbtf2.f \
  lapack/zpbtrf.f \
  lapack/zpbtrs.f \
  lapack/zpocon.f \
  lapack/zpotf2.f \
  lapack/zpotf2.f \
  lapack/zpotrf.f \
  lapack/zpotri.f \
  lapack/zpotrs.f \
  lapack/zptsv.f \
  lapack/zpttrf.f \
  lapack/zpttrf.f \
  lapack/zpttrs.f \
  lapack/zptts2.f \
  lapack/zrot.f \
  lapack/zsteqr.f \
  lapack/ztgevc.f \
  lapack/ztgevc.f \
  lapack/ztrcon.f \
  lapack/ztrevc.f \
  lapack/ztrexc.f \
  lapack/ztrsen.f \
  lapack/ztrsyl.f \
  lapack/ztrsyl.f \
  lapack/ztrti2.f \
  lapack/ztrtri.f \
  lapack/ztrtrs.f \
  lapack/ztzrzf.f \
  lapack/zung2l.f \
  lapack/zung2l.f \
  lapack/zung2r.f \
  lapack/zungbr.f \
  lapack/zunghr.f \
  lapack/zungl2.f \
  lapack/zunglq.f \
  lapack/zunglq.f \
  lapack/zungql.f \
  lapack/zungqr.f \
  lapack/zungtr.f \
  lapack/zunm2r.f \
  lapack/zunmbr.f \
  lapack/zunmbr.f \
  lapack/zunml2.f \
  lapack/zunmlq.f \
  lapack/zunmqr.f \
  lapack/zunmr3.f \
  lapack/zunmrz.f \
  lapack/zunmrz.f \
  lapack/chegs2.f \
  lapack/chegst.f \
  lapack/chegv.f \
  lapack/dsygs2.f \
  lapack/dsygst.f \
  lapack/dsygv.f \
  lapack/ssygs2.f \
  lapack/ssygst.f \
  lapack/ssygv.f \
  lapack/zhegs2.f \
  lapack/zhegst.f \
  lapack/zhegv.f

if AMCOND_HAVE_LAPACK
  EXTRA_DIST += $(LAPACK_SRC)
else
  libcruft_la_SOURCES += $(LAPACK_SRC)
endif
