EXTRA_DIST += \
  arpack/LICENSE \
  arpack/README \
  arpack/docs/debug.doc \
  arpack/docs/ex-complex.doc \
  arpack/docs/ex-nonsym.doc \
  arpack/docs/ex-sym.doc \
  arpack/docs/README \
  arpack/docs/stat.doc \
  arpack/src/module.mk \
  arpack/src/debug.h \
  arpack/src/stat.h \
  arpack/src/version.h \
  arpack/util/module.mk

libcruft_la_SOURCES += \
  arpack/src/cgetv0.f \
  arpack/src/cnaitr.f \
  arpack/src/cnapps.f \
  arpack/src/cnaup2.f \
  arpack/src/cnaupd.f \
  arpack/src/cneigh.f \
  arpack/src/cneupd.f \
  arpack/src/cngets.f \
  arpack/src/csortc.f \
  arpack/src/cstatn.f \
  arpack/src/dgetv0.f \
  arpack/src/dlaqrb.f \
  arpack/src/dnaitr.f \
  arpack/src/dnapps.f \
  arpack/src/dnaup2.f \
  arpack/src/dnaupd.f \
  arpack/src/dnaupe.f \
  arpack/src/dnconv.f \
  arpack/src/dneigh.f \
  arpack/src/dneupd.f \
  arpack/src/dngets.f \
  arpack/src/dsaitr.f \
  arpack/src/dsapps.f \
  arpack/src/dsaup2.f \
  arpack/src/dsaupd.f \
  arpack/src/dsconv.f \
  arpack/src/dseigt.f \
  arpack/src/dsesrt.f \
  arpack/src/dseupd.f \
  arpack/src/dsgets.f \
  arpack/src/dsortc.f \
  arpack/src/dsortr.f \
  arpack/src/dstatn.f \
  arpack/src/dstats.f \
  arpack/src/dstqrb.f \
  arpack/src/sgetv0.f \
  arpack/src/slaqrb.f \
  arpack/src/snaitr.f \
  arpack/src/snapps.f \
  arpack/src/snaup2.f \
  arpack/src/snaupd.f \
  arpack/src/snaupe.f \
  arpack/src/snconv.f \
  arpack/src/sneigh.f \
  arpack/src/sneupd.f \
  arpack/src/sngets.f \
  arpack/src/ssaitr.f \
  arpack/src/ssapps.f \
  arpack/src/ssaup2.f \
  arpack/src/ssaupd.f \
  arpack/src/ssconv.f \
  arpack/src/sseigt.f \
  arpack/src/ssesrt.f \
  arpack/src/sseupd.f \
  arpack/src/ssgets.f \
  arpack/src/ssortc.f \
  arpack/src/ssortr.f \
  arpack/src/sstatn.f \
  arpack/src/sstats.f \
  arpack/src/sstqrb.f \
  arpack/src/zgetv0.f \
  arpack/src/znaitr.f \
  arpack/src/znapps.f \
  arpack/src/znaup2.f \
  arpack/src/znaupd.f \
  arpack/src/zneigh.f \
  arpack/src/zneupd.f \
  arpack/src/zngets.f \
  arpack/src/zsortc.f \
  arpack/src/zstatn.f \
  arpack/util/cmout.f \
  arpack/util/cvout.f \
  arpack/util/dmout.f \
  arpack/util/dvout.f \
  arpack/util/icnteq.f \
  arpack/util/icopy.f \
  arpack/util/iset.f \
  arpack/util/iswap.f \
  arpack/util/ivout.f \
  arpack/util/second.f \
  arpack/util/smout.f \
  arpack/util/svout.f \
  arpack/util/zmout.f \
  arpack/util/zvout.f
